stories = Story.create([
  {author_id: User.find_by(username: 'wirving').id, title: "The Legend of Sleepy Hollow Part 1", body: @wirvingTLOSH_1},
  {author_id: User.find_by(username: 'wirving').id, title: "The Legend of Sleepy Hollow Part 2", body: @wirvingTLOSH_2},
  {author_id: User.find_by(username: 'iasimov').id, title: "The Last Question", body: @iasimovTLQ},
  {author_id: User.find_by(username: 'iasimov').id, title: "Gold", body: @iasimovG},
  {author_id: User.find_by(username: 'rbradbury').id, title: "The one who waits", body: @rbradburyTOWW},
  {author_id: User.find_by(username: 'rbradbury').id, title: "The Dog In The Red Bandana", body: @rbradburyTDITRB},
  {author_id: User.find_by(username: 'sking').id, title: "Children of the Corn Part 1", body: @skingCOTK_1},
  {author_id: User.find_by(username: 'sking').id, title: "Children of the Corn Part 2", body: @skingCOTK_2},
  {author_id: User.find_by(username: 'jdsalinger').id, title: "Once a Week Won't Kill You", body: @jdsalingerOAWWKY},
  {author_id: User.find_by(username: 'jdsalinger').id, title: "Go See Eddie", body: @jdsalingerGSE},
  {author_id: User.find_by(username: 'jdsalinger').id, title: "A Girl I knew", body: @jdsalingerAGIK},
  {author_id: User.find_by(username: 'ohenry').id, title: "The Last Leaf", body: @ohenryTLL},
  {author_id: User.find_by(username: 'ohenry').id, title: "The Ransom of Red Chief", body: @ohenryTRORC},
  {author_id: User.find_by(username: 'jupdike').id, title: "A&P", body: @jupdikeAP},
])
