comments = Comment.create([
{ commenter_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 2" ).id, body: "Oh lord what was I thinking" },
{ commenter_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "The Last Question" ).id, body: "I'd give this a two thumbs up!" },
{ commenter_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "Gold" ).id, body: "What a great story!" },
{ commenter_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "The one who waits" ).id, body: "Jesus, the ending.." },
{ commenter_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "Children of the Corn Part 1" ).id, body: "I think my story is scarier" },
{ commenter_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "Children of the Corn Part 2" ).id, body: "Oh wow, this story is so good!" },
{ commenter_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "Once a Week Won't Kill You" ).id, body: "What kind of propaganda is this?" },
{ commenter_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "A Girl I knew" ).id, body: "I knew a girl..." },
{ commenter_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "The Ransom of Red Chief" ).id, body: "Eh, this was okay" },
{ commenter_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "A&P" ).id, body: "The intro was so boring but the ending makes it worth it" },

{ commenter_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 1" ).id, body: "oooo scary..." },
{ commenter_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "The one who waits" ).id, body: "I wish I have that level of patience" },
{ commenter_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "The Dog In The Red Bandana" ).id, body: "what? this story doesn't make sence at all" },
{ commenter_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "Children of the Corn Part 2" ).id, body: "Check out my stories guys. It's alot better than this" },
{ commenter_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "Once a Week Won't Kill You" ).id, body: "I don't agree with any of this" },
{ commenter_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "Go See Eddie" ).id, body: "I liked this ! :D" },
{ commenter_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "The Last Leaf" ).id, body: "woah I love the ending!" },
{ commenter_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "A&P" ).id, body: "Couldn't you pick a better title" },

{ commenter_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 1" ).id, body: "why would you split it into two parts?" },
{ commenter_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "Gold" ).id, body: "this story was...gold." },
{ commenter_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "Children of the Corn Part 1" ).id, body: "the cliff hanger, oh baby." },
{ commenter_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "Once a Week Won't Kill You" ).id, body: "I'm not quitting!" },
{ commenter_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "A Girl I knew" ).id, body: "what a sad story" },
{ commenter_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "The Last Leaf" ).id, body: "meh It was okay" },
{ commenter_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "The Ransom of Red Chief" ).id, body: "What was the whole point of this story?" },
{ commenter_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "A&P" ).id, body: "Loved it!" },

{ commenter_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 1" ).id, body: "Oh boy, I can't wait for part two" },
{ commenter_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 2" ).id, body: "What an ending! Bravo!" },
{ commenter_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "The Last Question" ).id, body: "great story!" },
{ commenter_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "Gold" ).id, body: "what a lovely tale" },
{ commenter_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "The one who waits" ).id, body: "I loved this!" },
{ commenter_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "The Dog In The Red Bandana" ).id, body: "Your other work was better" },
{ commenter_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "Once a Week Won't Kill You" ).id, body: "More people should read this story" },
{ commenter_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "Go See Eddie" ).id, body: "what are you doing reading the comment! scroll back up!" },
{ commenter_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "A Girl I knew" ).id, body: "welp, didn't expect that ending" },
{ commenter_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "The Last Leaf" ).id, body: "I can write a much better story than this" },
{ commenter_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "The Ransom of Red Chief" ).id, body: "Honetly, i stopped reading mid way" },
{ commenter_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "A&P" ).id, body: "boring!" },

{ commenter_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 1" ).id, body: "Oh boy I can't wait for the second part!" },
{ commenter_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 2" ).id, body: "Honestly, this was a let down" },
{ commenter_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "The Last Question" ).id, body: "Hey dude, can you get in touch with me? I wanna work with you" },
{ commenter_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "Gold" ).id, body: "this story is amazing" },
{ commenter_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "The one who waits" ).id, body: "The main content wasn't too solid" },
{ commenter_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "The Dog In The Red Bandana" ).id, body: "Wow, I'm speachless..." },
{ commenter_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "Children of the Corn Part 1" ).id, body: "This should be adapted into a movie!" },
{ commenter_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "Children of the Corn Part 2" ).id, body: "I'm so gonna share this on my fb" },
{ commenter_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "The Ransom of Red Chief" ).id, body: "what a boring story" },
{ commenter_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "A&P" ).id, body: "Okay, i feel this" },

{ commenter_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 1" ).id, body: "I like what I see so far" },
{ commenter_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 2" ).id, body: "This was a let down. sorry man." },
{ commenter_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "The Last Question" ).id, body: "boooooo! boring!" },
{ commenter_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "Gold" ).id, body: "I kind of like this one" },
{ commenter_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "Children of the Corn Part 2" ).id, body: "Sleepy Hollow is scarier" },
{ commenter_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "Go See Eddie" ).id, body: "Can you please write about anything else but this?" },
{ commenter_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "A Girl I knew" ).id, body: "Will you publish this in physical print? I have to get my hand on htis" },
{ commenter_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "A&P" ).id, body: "I loved it so much!" },

{ commenter_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 1" ).id, body: "When will you release part two?" },
{ commenter_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 2" ).id, body: "How can people not like this" },
{ commenter_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "Gold" ).id, body: "Yo, you deserve more attention from the public" },
{ commenter_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "The one who waits" ).id, body: "nah fam, you can just keep waiting you know." },
{ commenter_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "The Dog In The Red Bandana" ).id, body: "that dog is fam" },
{ commenter_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "Children of the Corn Part 1" ).id, body: "I liked sleepy Hollow more" },
{ commenter_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "Children of the Corn Part 2" ).id, body: "I was wrong, i love this so much more" },
{ commenter_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "A Girl I knew" ).id, body: "If I know a girl like that..." },
{ commenter_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "The Last Leaf" ).id, body: "I don't get any of this, at all" },
])
