likes = Like.create([
  { user_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 1" ).id },
  { user_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "Gold" ).id },
  { user_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "The Dog In The Red Bandana" ).id },
  { user_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "Children of the Corn Part 1" ).id },
  { user_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "Once a Week Won't Kill You" ).id },
  { user_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "Go See Eddie" ).id },
  { user_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "The Last Leaf" ).id },
  { user_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "The Ransom of Red Chief" ).id },
  { user_id: User.find_by(username: "wirving").id, story_id: Story.find_by(title: "A&P" ).id },

  { user_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 1" ).id },
  { user_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "The Last Question" ).id },
  { user_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "Gold" ).id },
  { user_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "The Dog In The Red Bandana" ).id },
  { user_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "Children of the Corn Part 1" ).id },
  { user_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "Once a Week Won't Kill You" ).id },
  { user_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "Go See Eddie" ).id },
  { user_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "The Last Leaf" ).id },
  { user_id: User.find_by(username: "iasimov").id, story_id: Story.find_by(title: "The Ransom of Red Chief" ).id },

  { user_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 1" ).id },
  { user_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 2" ).id },
  { user_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "Gold" ).id },
  { user_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "The one who waits" ).id },
  { user_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "The Dog In The Red Bandana" ).id },
  { user_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "Children of the Corn Part 2" ).id },
  { user_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "Go See Eddie" ).id },
  { user_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "A Girl I knew" ).id },
  { user_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "The Last Leaf" ).id },
  { user_id: User.find_by(username: "rbradbury").id, story_id: Story.find_by(title: "The Ransom of Red Chief" ).id },

  { user_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 1" ).id },
  { user_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 2" ).id },
  { user_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "The Last Question" ).id },
  { user_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "The one who waits" ).id },
  { user_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "The Dog In The Red Bandana" ).id },
  { user_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "Children of the Corn Part 2" ).id },
  { user_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "Go See Eddie" ).id },
  { user_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "A Girl I knew" ).id },
  { user_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "The Ransom of Red Chief" ).id },
  { user_id: User.find_by(username: "sking").id, story_id: Story.find_by(title: "A&P" ).id },

  { user_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 1" ).id },
  { user_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "The Last Question" ).id },
  { user_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "Gold" ).id },
  { user_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "Children of the Corn Part 1" ).id },
  { user_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "Children of the Corn Part 2" ).id },
  { user_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "Once a Week Won't Kill You" ).id },
  { user_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "A Girl I knew" ).id },
  { user_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "The Ransom of Red Chief" ).id },
  { user_id: User.find_by(username: "jdsalinger").id, story_id: Story.find_by(title: "A&P" ).id },

  { user_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 1" ).id },
  { user_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 2" ).id },
  { user_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "The Last Question" ).id },
  { user_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "The one who waits" ).id },
  { user_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "The Dog In The Red Bandana" ).id },
  { user_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "Once a Week Won't Kill You" ).id },
  { user_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "Go See Eddie" ).id },
  { user_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "The Last Leaf" ).id },
  { user_id: User.find_by(username: "ohenry").id, story_id: Story.find_by(title: "A&P" ).id },

  { user_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "The Legend of Sleepy Hollow Part 2" ).id },
  { user_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "The Last Question" ).id },
  { user_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "The one who waits" ).id },
  { user_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "Children of the Corn Part 2" ).id },
  { user_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "Go See Eddie" ).id },
  { user_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "The Ransom of Red Chief" ).id },
  { user_id: User.find_by(username: "jupdike").id, story_id: Story.find_by(title: "A&P" ).id },

])
