follows = Follow.create([
  {followee_id: wirving, follower_id: iasimovy},
  {followee_id: wirving, follower_id: skingr},
  {followee_id: wirving, follower_id: ohenry},
  {followee_id: wirving, follower_id: jupdike},
  {followee_id: iasimov, follower_id: wirving},
  {followee_id: iasimov, follower_id: rbradbury},
  {followee_id: iasimov, follower_id: sking},
  {followee_id: iasimov, follower_id: ohenry},
  {followee_id: iasimov, follower_id: jupdike},
  {followee_id: rbradbury, follower_id: wirving},
  {followee_id: rbradbury, follower_id: iasimov},
  {followee_id: rbradbury, follower_id: sking},
  {followee_id: rbradbury, follower_id: jdsalinger},
  {followee_id: rbradbury, follower_id: ohenry},
  {followee_id: sking, follower_id: wirving},
  {followee_id: sking, follower_id: iasimov},
  {followee_id: sking, follower_id: jdsalinger},
  {followee_id: sking, follower_id: jupdike},
  {followee_id: jdsalinger, follower_id: wirving},
  {followee_id: jdsalinger, follower_id: iasimov},
  {followee_id: jdsalinger, follower_id: rbradbury},
  {followee_id: jdsalinger, follower_id: sking},
  {followee_id: jdsalinger, follower_id: jupdike},
  {followee_id: ohenry, follower_id: iasimov},
  {followee_id: ohenry, follower_id: rbradbury},
  {followee_id: ohenry, follower_id: sking},
  {followee_id: ohenry, follower_id: jdsalinger},
  {followee_id: ohenry, follower_id: jupdike},
  {followee_id: jupdike, follower_id: wirving},
  {followee_id: jupdike, follower_id: iasimov},
  {followee_id: jupdike, follower_id: rbradbury},
  {followee_id: jupdike, follower_id: jdsalinger},
  {followee_id: jupdike, follower_id: ohenry},

])
