@jdsalingerAGIK = %Q[At the end of my freshman year of college, back in 1936, I flunked five out of five subjects. Flunking three out of five would have made me eligible to report for an invitation to attend some other college in the fall. But men in this three-out-of-five category sometimes had to wait outside the Dean's office as long as two hours. Men in my group - some of whom had big dates in New York that same night - weren't kept waiting a minute. It went one, two, three, the way most men in my group like things to go.
The particular college I had been attending apparently does not simply mail people's grades home, but prefers to shoot them out of some kind of gun. When I got home to New York, even the butler looked tipped off and hostile. It was a bad night altogether. My father informed me quietly that my formal education was formally over. In a way, I felt like asking for a crack at summer school or something. But I didn't. For one reason, my mother was in the room, and she kept saying that she just knew I should have gone to see my faculty adviser more regularly, that that was what he was there for. This was the kind of talk that made me want to go straight to the Rainbow Room with a friend. At any rate, one thing leading to another, when the familiar moment came to me to advance one of my fragile promises really to apply myself this time, I let it go by unused.
Although my father announced the same night that he was going to put me directly into his business, I felt confident that nothing wholly unattractive would happen for at least a week or so. I knew it would take a certain amount of deep, constructive brooding on my father's part to figure out a way of getting me into the firm in broad daylight - I happened to give both his partners the willies on sight.
I was taken a little aback, four or five evenings later, when my father suddenly asked me at dinner how I would like to go to Europe to learn a couple of languages the firm could use. First to Vienna and then maybe to Paris, he said unelaborately.
I replied in the effect that the idea sounded all right to me. I was breaking off anyway with a certain girl on Seventy-Fourth Street. And I very clearly associated Vienna with gondolas. Gondolas didn't seem like too bad a setup.

A few weeks later, in July of 1936, I sailed for Europe. My passport photograph, it might be worth mentioning, looked exactly like me. At eighteen I was six feet two, weighed 119 pounds with my clothes on, and was a chain smoker. I think that if Goethe's Werther and all his sorrows had been placed on the promenade deck of the S.S. Rex beside me and all my sorrows, he would have looked by comparison, like a rather low comedian.
The ship docked at Naples, and from there I took a train to Vienna. I almost got off the train at Venice, when I found out just who had the gondolas, but two people in my compartment got off instead - I had been waiting too long for a chance to put my feet up, gondolas or no gondolas.
Naturally, certain when-you-get-to-Vienna rules had been laid down before my ship sailed from New York. Rules about taking at least three hours of language lessons daily; rules about not getting too friendly with people who take advantage of other, particularly younger, people; rules about not spending money like a drunken sailor; rules about the wearing of clothes in which a person wouldn't catch pneumonia; and so on. But after a month or so in Vienna I had most of that taken care of: I was taking three hours of German lesson every day - from a rather exceptional young lady I had met in the lounge of the Grand Hotel. I had found, in one of the far-outlying districts, a place that was cheaper than the Grand Hotel - the trolleys didn't run to my place after ten at night, but the taxis did. I was dressing warm - I had bought myself three pure-wool Tyrolean hats. I was meeting nice people - I had lent three hundred shillings to a very distinguished-looking guy in the bar of the Bristol Hotel. In short, I was in a position to cut my letter home down to the bone.
I spent a little more than five months in Vienna. I danced. I went ice skating and skiing. For strenuous exercise, I argued with an Englishman. I watched operations at two hospitals and had myself psychoanalyzed by a young Hungarian woman who smoked cigars. My German lessons never failed to hold my unflagging interest. I seemed to move, with all the luck of the undeserving, from gemutlichkeit to gemutlichkeit. But I mention these only to keep the Baedeker straight.
Probably for every man there is at least one city that sooner or later turns into a girl. How well or how badly the man actually knew the girl doesn't necessarily affect the transformation. She was there, and she was the whole city, and that's that.
Leah was the daughter in the Viennese-Jewish family who lived in the apartment below mine - that is, below the family I was boarding with. She was sixteen, and beautiful in an immediate yet perfectly slow way. She had very dark hair that fell away from the most exquisite pair of ears I have ever seen. She had immense eyes that always seemed in danger of capsizing in their own innocence. Her hands were very pale brown, with slender, actionless fingers. When she sat down, she did the only sensible thing with her beautiful hands there was to be done: she placed them on her lap and left them there. In brief, she was probably the first appreciable thing of beauty I had seen that struck me as wholly legitimate.
For about four months I saw her two or three evenings a week, for an hour or so at a time. But never outside the apartment house in which we lived. We never went dancing; we never went to a concert; we never even went for a walk. I found out soon after we met that Leah's father had promised her in marriage to some young Pole. Maybe this fact had something to do with my not quite palpable, but curiously steady disinclination to give our acquaintanceship the run of the city. Maybe I just worried too much about things. Maybe I consistently hesitated to risk letting the thing we had together deteriorate into a romance. I don't know any more. I used to know, but I lost the knowledge a long time ago. A man can't go along indefinitely carrying around in his pocket a key that doesn't fit anything.
I met Leah a nice way.
I had a phonograph and two American phonograph records in my room. The two American records were a gift from my landlady - one of those rare, drop-it-and-run gifts that leave the recipient dizzy with gratitude. On one of the records Dorothy Lamour sang Moonlight and Shadows, and on the other Connie Boswell sang Where Are You? Both girls got pretty scratched up, hanging around my room, as they had to go to work whenever I heard my landlady's step outside my door.
One evening I was in my sitting room, writing a long letter to a girl in Pennsylvania, suggesting that she quit school and come to Europe to marry me; a not infrequent suggestion of mine in those days. My phonograph was not playing. But suddenly the words to Miss Boswell's song floated, just slightly damaged, through my open window:
Where are you? Where have you gone wissout me? I sought you cared about me. Where are you?
Thoroughly excited, I sprang to my feet, then rushed to my window and leaned out.
The apartment below mine had the only balcony of the house. I saw a girl standing on it, completely submerged in the pool of autumn twilight. She wasn't doing a thing that I could see, except standing there leaning on the balcony railing, holding the universe together. The way the profile of her face and body refracted in the soupy twilight made me feel a little drunk. When a few seconds had throbbed by, I said hello to her. She then looked up at me, and though she seemed decorously startled, something told me she wasn't too surprised that I had heard her doing the Boswell number. This didn't matter, of course. I asked her, in murderous German, if I might join her on the balcony. The request obviously rattled her. She replied, in English, that she didn't think her 'fahzzer' would like me to come down to see her. At this point, my opinion of girls' fathers, which had been low for years, struck bottom. But nevertheless I managed a drab little nod of understanding.
It turned out all right, though. Leah seemed to think it would be perfectly all right if she came up to see me. Entirely stupefied with gratitude, I nodded, then closed my window and began to wander hurriedly through my room, rapidly pushing things under other things with my foot.

I don't really remember our first evening in my sitting room. All our evenings were pretty much the same. I can't honestly separate one from another; not anymore, anyway.
Leah's knock on my door was always poetry - high, beautifully wavering, absolutely perpendicular poetry. Her knock started out speaking of her own innocence and beauty, and accidentally ended speaking of the innocence and beauty of all very young girls. I was always half-eaten away by the respect and happiness when I opened the door for Leah.
We would solemnly shake hands at my sitting-room door. Then Leah would walk, self-consciously but beautifully, to my window seat, sit down, and wait for our conversation to begin.
Her English, like my German, was nearly all holes. Yet invariably I spoke her language and she mine, although any other arrangement at all might have made for a less perforated means of communication.
"Uh. Wie geht es Ihnen?" I'd start out. (How are you?) I never used the familiar form in addressing Leah.
"I am very well, sank you very much," Leah would reply, never failing to blush. It didn't help much to look at her indirectly; she blushed anyway.
"Schon hinaus, nicht wahr?" I'd ask, rain or shine. (Nice out, isn't it?)
"Yes," she'd answer, rain or shine.
"Uh. Waren Sie heute in der Kino?" was a favorite question of mine. (Did you go to the movies today?) Five days a week Leah worked in her father's cosmetics plant.
"No. I was today working by my fahzzer."
"Oh, dass ist recht! Uh. Ist es schon dort?" (Oh, that's right. Is it nice there?)
"No. It is a very big fabric, with very many people running around about."
"Oh. Dass ist schlecht." (That's bad.)
"Uh. Wollen Sie haben ein Tasse von Kaffee mit mir haben?" (Will you have a cup of coffee with me?)
"I was already eating."
"Ja, aber Haben Sie ein Tasse anyway." (Yes, but have a cup anyway.)
"Sank you."
At this point I would remove my note paper, shoe trees, laundry, and other unclassifiable articles from the small table I used as a desk and a catchall. Then I would plug in my electric percolator, often commenting sagely, "Kaffee ist gut." (Coffee is good.)
We usually drank two cups of coffee apiece, passing each other the cream and sugar with all the drollery of fellow pallbearers distributing white gloves among themselves. Often Leah brought along some kuchen or torte, wrapped rather inefficiently - perhaps surreptitiously - in waxed paper. This offering she would deposit quickly and insecurely in my left hand as she entered my sitting room. It was all I could do to swallow the pastry Leah brought. First, I was never at all hungry while she was around; second, there seemed to be something unnecessarily, however vaguely, destructive about eating anything that came from where she lived.
We usually didn't talk while we drank our coffee. When we had finished, we picked up our conversation where we had left it - on it's back, more often than not.
"Uh. Ist die Fenster - uh - Sind Sie sehr kalt dort?" I would ask solicitously. (Is the window - uh - Are you very cold there?)
"No! I feel very warmly, sank you."
"Dass ist gut. Uh. Wie geht's Ihre Eltern?" (That's good. How are your parents?) I inquired regularly after the health of her parents.
"They are very well, sank you very much." Her parents were always enjoying perfect health, even when her mother had pleurisy for two weeks.
Sometimes Leah introduced a subject for conversation. It was always the same subject, but probably she felt she handled it so well in English that repetition was little or no drawback. She often inquired, "How was your hour today morning?"
"My German lesson? Oh. Uh. Sehr gut. Ja. Sehr gut." (Very good. Yes. Very good.)
"What were you learning?"
"What did I learn? Uh. Die, uh wuddayacallit. Die starke verbs. Sehr interessant." (The strong verbs. Very interesting.)

I could fill several pages with Leah's and my terrible conversation. But I don't see much point to it. We just never said anything to each other. Over a period of four months, we must have talked for thirty or thirty-five evenings without saying a word. In the long shadow of this small, obscure record, I've acquired a dogma that if I should go to Hell, I'll be given a little inside room - one that is neither hot nor cold, but extremely drafty - in which all my conversations with Leah will be played back to me, over an amplification system confiscated from Yankee Stadium.
One evening I named for Leah, without the slightest provocation, all the Presidents of the United States, in as close order as possible: Lincoln, Grant, Taft, and so on.
Another evening I explained American football to her. For at least an hour and a half. In German.
On another evening I felt called on to draw her a map of New York. She certainly didn't ask me to. And Lord knows I never feel like drawing maps for anybody, much less have any aptitude for it. But I drew it - the U.S Marines couldn't have stopped me. I distinctly remember putting Lexington Avenue where Madison should have been - and leaving it that way.
Another time I read a new play I was writing, called He Was No Fool. It was about a cool, handsome, casually athletic young man - very much my own type - who had been called from Oxford to pull Scotland Yard out of an embarrassing situation:
One Lady Farnsworth, who was a witty dipsomaniac, was being mailed one of her abducted husband's fingers every Tuesday. I read the play to Leah in one sitting, laboriously editing out all the sexy parts - which, of course, ruined the play. When I had finished reading, I hoarsely explained to Leah that the play was "Nicht fertig yet." (Not finished yet.) Leah seemed to understand perfectly. Moreover, she seemed to convey to me a certain confidence that perfection would somehow overtake the final draft of whatever the thing was I had just read to her. She sat so well on a window seat.

I found out entirely by accident that Leah had a fianc‚. It wasn't the kind of information that stood a chance of coming up in our conversation.
On a Sunday afternoon, about a month after Leah and I had become acquainted, I saw her standing in the crowded lobby of the Schwedenkino, a popular movie house in Vienna. It was the first time I had seen her either off the balcony or outside my sitting room. There was something fantastic and extremely heady about seeing her standing in the pedestrian lobby of the Schwedenkino, and I readily gave up my place in the box-office queue to go to speak to her. But as I charged across the lobby toward her over a number of innocent feet, I saw that she was neither alone nor with a girl friend or someone old enough to be her father.
She was visibly flustered to see me, but managed to make introductions. Her escort, who was wearing his hat down over one of his ears, clicked his heels and crushed my hand. I smiled patronizingly at him - he didn't look like much competition, grip of steel or no grip of steel; he looked too much like a foreigner.
For a few minutes the three of us chatted unintelligibly. Then I excused myself and got back on the end of the line. During the showing of the film, I went up the aisle several times, carrying myself as erectly and dangerously as possible; but I didn't see either of them. The film itself was one of the worst I'd seen.
The next evening, when Leah and I had coffee in my sitting room, she stated, blushing, that the young man I had seen her with in the lobby of the Schwedenkino was her fianc‚.
"My fahzzer is wedding us when I have seventeen years," Leah said, looking at a doorknob.
I merely nodded. There a certain foul blows, notably in love and soccer, that are not immediately followed by audible protest. I cleared my throat. "Uh. Wie heisst er, again?" (What's his name, again?)
Leah pronounced once more - not quite phonetically enough for me - a violently long name, which seemed to me predestined to belong to somebody who wore his hat down over one ear. I poured more coffee for both of us. Then, suddenly, I stood up and went to my German-English dictionary. When I had consulted it, I sat down again and asked Leah, "Lieben Sie Ehe?" (Do you love marriage?)
She answered slowly, without looking at me, "I don't know."
I nodded. Her answer seemed the quintessence of logic to me. We sat for a long moment without looking at each other. When I looked at Leah again, her beauty seemed too great for the size of the room. The only way to make room for it was to speak of it. "Sie sind sehr schon. Weissen Sie dass?" I almost shouted at her.
But she blushed so hard I quickly dropped the subject - I had nothing to follow up with, anyway.
That evening, for the first and last time, something more physical than a handshake happened to our relationship. About nine-thirty, Leah jumped up from the window seat, saying it was becoming very late, and rushed to get downstairs. At the same time, I rushed to escort her out of the apartment to the staircase, and we squeezed together through the narrow doorway of my sitting room - facing each other. It nearly killed us.
When it came time for me to go to Paris to master a second European language, Leah was in Warsaw visiting her fianc‚'s family. I didn't get to say good-bye to her, but I left a note for her, the next-to-last draft of which I still have:
Wien December 6, 1936
Liebe Leah,
Ich muss fahren nach Paris nun, und so ich sage auf wiedersehen. Es war sehr nett zu kennen Sie. Ich werde schreiben zu Sie wenn ich bin in Paris. Hoffentlich Sie sind haben eine gute Ziet in Warsaw mit die familie von ihre fianc‚. Hoffentlich wird die Ehe gehen gut. Ich werde Sie schicken das Buch ich habe gesprochen iiber, 'Gegangen mit der Wind.' Mit beste Grussen.
Ihre Freund
John
Taking this note out of Jack-the-Ripper German, it reads:
Vienna December 6, 1936
Dear Leah
I must go to Paris now, and so I say good-bye. It was very nice to know you. I hope you're having a good time in Warsaw with your fiance's family. I hope the marriage goes all right. I will send you that book I was talking about, Gone with the Wind. With best greetings,
Your friend,
John
But I never did write to Leah from Paris. I never wrote to her again at all. I didn't send a copy of Gone with the Wind. I was very busy in those days. Late in 1937, when I was back in college in America, a round, flat package was forwarded to me from New York. A letter was attached to the package:
Vienna October 14, 1937
Dear John,
I have many times thought of you and wondered what is become of you. I myself am now married and am living in Vienna with my husband. He sends you his great regards. If you can recall, you and he made each other's acquaintance in the hall of the Schweden Cinema. My parents are still living at 18 Stiefel Street, and often I visit them, because I am living in the near. Your landlady, Mrs. Schlosser, has died in the summer with cancer. She requested me to send you these gramophone records, which you forgot to take when you departed, but I did not know your address for a long time. I have now made the acquaintance of an English girl named Ursula Hummer, who has given to me your address. My husband and I would be extremely pleased to hear from you frequently
With very best greetings,
Your friend,
Leah
Her married name and new address were not given.
I carried the letter with me for months, opening and reading it in bars, between halves of basketball games, in Government classes, and in my room, until finally it began to get stained, from my wallet, the color of cordovan, and I had to put it away somewhere.
About the same hour Hitler's troops were marching into Vienna, I was on reconnaissance for geology 1-b, searching perfunctorily, in New Jersey, for a limestone deposit. But during the weeks and months that followed the German takeover of Vienna, I often thought of Leah. Sometimes just thinking of her wasn't enough. When, for example, I had examined the most recent newspaper photographs of Viennese Jewesses on their hands and knees scrubbing the sidewalks, I quickly stepped across my dormitory room, opened a desk drawer, slipped an automatic into my pocket, then dropped noiselessly from my window to the street, where a long-range monoplane, equipped with a silent engine, awaited my gallant, foolhardy, hawklike whim. I'm not the type that just sits around.
In late summer of 1940, at a party in New York, I met a girl who not only had known Leah in Vienna, but had gone all through school with her. I pulled up a chair, but the girl was determined to tell me about some man in Philadelphia, who looked exactly like Gary Cooper. She said I had a weak chin. She said she hated mink. She said that Leah had either got out of Vienna or hadn't got out of Vienna.
During the war in Europe, I had an Intelligence job with a regiment of an infantry division. My work called for a lot of conversation with civilians and Wehrmacht prisoners. Among the latter, sometimes there were Austrians. One feldwebel, a Viennese, whom I secretly suspected of wearing lederhosen under his field-gray uniform, gave me a little hope: but it turned out he had known not Leah, but some girl with the same last name as Leah's. Another Wiener, an unteroffizier, standing at strict attention, told me what terrible things had been done to the Jews in Vienna. As I had rarely, if ever, seen a man with a face quite so noble and full of vicarious suffering as this unteroffizier's was, just for the devil of it I had him roll up his left sleeve. Close to his armpit he had the tattooed blood-type marks of an old SS man. I stopped asking personal questions after a while.
A few months after the war in Europe had ended, I took some military papers to Vienna. In a jeep with another man, I left Nurnburg on a hot October morning and got into Vienna the next, even hotter, morning. In the Russian Zone we were detained five hours while two guards made passionate love to our wrist watches. It was midafternoon by the time we entered the American Zone of Vienna, in which Stiefelstrasse, my old street, was located.
I talked to the Tabak-Trafik vendor on the corner of Stiefelstrasse, to the pharmacist in the near-by Apotheke, to a neighborhood woman, who jumped at least an inch when I addressed her, and to a man who insisted that he used to see me on the trolley car in 1936. Two of these people told me that Leah was dead. The pharmacist suggested that I go to see a Dr. Weinstein, who had just come back from Vienna from Buchenwald, and gave me his address. I then got back into the jeep, and we cruised through the streets toward G-2 Headquarters. My jeep partner tooted his horn at the girls in the streets and told me at great length what he thought of Army dentists.
When we had delivered the official papers, I got back into the jeep alone and went to see Dr. Weinstein.

It was twilight when I drove back to Stiefelstrasse. I parked the jeep and entered my old house. It had been turned into living quarters for field-grade officers. A red-haired staff sergeant was sitting at an Army desk on the first landing, cleaning his fingernails. He looked up, and, as I didn't outrank him, gave that long Army look that holds no interest or curiosity at all. Ordinarily I would have returned it.
"What's the chances of my going up to the second floor just for a minute?" I asked. "I used to live here before the war."
"This here's officers' quarters, Mac," he said.
"I know. I'll only be a minute."
"Can't do it. Sorry." He went on scraping the insides of his fingernails with the big blade of his pocket knife.
"I'll only be a minute," I said again.
He put down his knife, patiently. "Look, Mac. I don't wanna sound like a bum. But I ain't lettin nobody go upstairs unless they belong there. I don't give a damn if it's Eisenhower himself. I got my - " He was interrupted by the sudden ringing of a telephone on his desk. He picked up the phone, keeping an eye on me, and said, "Yessir, Colonel, sir. This is him on the phone..Yessir..Yessir..I got Corporal Santini puttin' 'em on the ice right now, right this minute. They'll be good and cold..Well, I figured we'd put the orchestra right out on the balcony, like. Account of there's only three of 'em..Yessir..Well, I spoke to Major Foltz, and he said the ladies could put their coats and stuff in his room..Yessir. Right, sir. Ya wanna hurry up, now. Ya don't wanna miss any of that moonlight..Ha,ha,ha!..Yessir. G'bye, sir." The staff sergeant hung up, looking stimulated.
"Look," I said, distracting him, "I'll only be a minute."
He looked at me. "What's the big deal, anyhow, up there?"]
