@jupdikeAP = %[<p>In walks these three girls in nothing but bathing suits. I'm in the third check-out slot, with my back to the door, so I don't see them until they're over by the bread. The one that caught my eye first was the one in the plaid green two-piece. She was a chunky kid, with a good tan and a sweet broad soft-looking can with those two crescents of white just under it, where the sun never seems to hit, at the top of the backs of her legs. I stood there with my hand on a box of HiHo crackers trying to remember if I rang it up or not. I ring it up again and the customer starts giving me hell. She's one of these cash-register-watchers, a witch about fifty with rouge on her cheekbones and no eyebrows, and I knowit made her day to trip me up. She'd been watching cash registers forty years and probably never seen a mistake before.</p>
<p>By the time I got her feathers smoothed and her goodies into a bag -- she gives me alittle snort in passing, if she'd been born at the right time they would have burned her over in Salem -- by the time I get her on her way the girls had circled around the bread and were coming back, without a pushcart, back my way along the counters, in the aisle between the check-outs and the Special bins. They didn't even have shoes on. There was this chunky one, with the two-piece -- it was bright green and the seams on the bra were still sharp and her belly was still pretty pale so I guessed she just got it (the suit) -- there was this one, with one of those chubby berry-faces, the lips all bunched together under her nose, this one, and a tall one, with black hair that hadn't quite frizzed right, and one of these sunburns right across under the eyes, and a chin that was too long -- you know, the kind of girl other girls think is very "striking" and "attractive" but never quite makes it, as they very well know, which is why they like her so much -- and then the third one, that wasn't quite so tall. She was the queen. She kind of led them, the other two peeking around and making their shoulders round. She didn't look around, not this queen, she just walked straight on slowly, on these long white prima donna legs. She came down a little hard on her heels, as if she didn't walk in her bare feet that much, putting down her heels and then letting the weight move along to her toes as if she was testing the floor with every step, putting a little deliberate extra action into it. You never know for sure how girls' minds work (do you really think it's a mind in there or just a little buzz like a bee in a glassjar?) but you got the idea she had talked the other two into coming in here with her, and now she was showing them how to do it, walk slow and hold yourself straight.</p>
<p>She had on a kind of dirty-pink - - beige maybe, I don't know -- bathing suit with a little nubble all over it and, what got me, the straps were down. They were off her shoulders looped loose around the cool tops of her arms, and I guess as a result the suit had slipped a little on her, so all around the top of the cloth there was this shining rim. If it hadn't been there you wouldn't have known there could have been anything whiter than those shoulders. With the straps pushed off, there was nothing between the top of the suit and the top of her head except just her, this clean bare plane of the top of her chest down from the shoulder bones like a dented sheet of metal tilted in the light. I mean, it was more than pretty.</p>
<p>She had sort of oaky hair that the sun and salt had bleached, done up in a bun that was unravelling, and a kind of prim face. Walking into the A &amp; P with your straps down, I suppose it's the only kind of face you <em>can</em> have. She held her head so high her neck, coming up out o fthose white shoulders, looked kind of stretched, but I didn't mind. The longer her neck was, the more of her there was.</p>
<p>She must have felt in the corner of her eye me and over my shoulder Stokesie in the second slot watching, but she didn't tip. Not this queen. She kept her eyes moving across the racks, and stopped, and turned so slow it made my stomach rub the inside of my apron, and buzzed to the other two, who kind of huddled against her for relief, and they all three of them went up the cat-and-dog-food-breakfast-cereal-macaroni-ri ce-raisins-seasonings-spreads-spaghetti-soft drinks- rackers-and- cookies aisle. From the third slot I look straight up this aisle to the meat counter, and I watched them all the way. The fat one with the tan sort of fumbled with the cookies, but on second thought she put the packages back. The sheep pushing their carts down the aisle -- the girls were walking against the usual traffic (not that we have one-way signs or anything) -- were pretty hilarious. You could see them, when Queenie's white shoulders dawned on them, kind of jerk, or hop, or hiccup, but their eyes snapped back to their own baskets and on they pushed. I bet you could set off dynamite in an A &amp; P and the people would by and large keep reaching and checking oatmeal off their lists and muttering "Let me see, there was a third thing, began with A, asparagus, no, ah, yes, applesauce!" or whatever it is they do mutter. But there was no doubt, this jiggled them. A few house-slaves in pin curlers even looked around after pushing their carts past to make sure what they had seen was correct.</p>
<p>You know, it's one thing to have a girl in a bathing suit down on the beach, where what with the glare nobody can look at each other much anyway, and another thing in the cool of the A &amp; P, under the fluorescent lights, against all those stacked packages, with her feet paddling along naked over our checkerboard green-and-cream rubber-tile floor.</p>
<p>"Oh Daddy," Stokesie said beside me. "I feel so faint."</p>
<p>"Darling," I said. "Hold me tight." Stokesie's married, with two babies chalked up on his fuselage already, but as far as I can tell that's the only difference. He's twenty-two, and I was nineteen this April.</p>
<p>"Is it done?" he asks, the responsible married man finding his voice. I forgot to say he thinks he's going to be manager some sunny day, maybe in 1990 when it's called the Great Alexandrov and Petrooshki Tea Company or something.</p>
<p>What he meant was, our town is five miles from a beach, with a big summer colony out on the Point, but we're right in the middle of town, and the women generally put on a shirt or shorts or something before they get out of the car into the street. And anyway these are usually women with six children and varicose veins mapping their legs and nobody, including them, could care less. As I say, we're right in the middle of town, and if you stand at our front doors you can see two banks and the Congregational church and the newspaper store and three real-estate offices and about twenty-seven old free-loaders tearing up Central Street because the sewer broke again. It's not as if we're on the Cape; we're north of Boston and there's people in this town haven't seen the ocean for twenty years.</p>
<p>The girls had reached the meat counter and were asking McMahon something. He pointed, they pointed, and they shuffled out of sight behind a pyramid of Diet Delight peaches. All that was left for us to see was old McMahon patting his mouth and looking after them sizing up their joints. Poor kids, I began to feel sorry for them, they couldn't help it. </p>
<p>Now here comes the sad part of the story, at:least my family says it's sad but I don't think it's sad myself. The store's pretty empty, it being Thursday afternoon, so there was nothing much to do except lean on the register and wait for the girls to show up again. The whole store was like a pinball machine and I didn't know which tunnel they'd come out of. After a while they come around out of the far aisle, around the light bulbs, records at discount of the Caribbean Six or Tony Martin Sings or some such gunk you wonder they waste the wax on, sixpacks of candy bars, and plastic toys done up in cellophane that faIl apart when a kid looks at them anyway. Around they come, Queenie still leading the way, and holding a little gray jar in her hand. Slots Three through Seven are unmanned and I could see her wondering between Stokes and me, but Stokesie with his usual luck draws an old party in baggy gray pants who stumbles up with four giant cans of pineapple juice (what do these bums <em>do</em> with all that pineapple juice' I've often asked myself) so the girls come to me. Queenie puts down the jar and I take it into my fingers icy cold. Kingfish Fancy Herring Snacks in Pure Sour Cream: 49&cent;. Now her hands are empty, not a ring or a bracelet, bare as God made them, and I wonder where the money's coming from. Still with that prim look she lifts a folded dollar bill out of the hollow at the center of her nubbled pink top. The jar went heavy in my hand. Really, I thought that was so cute.</p>
<p>Then everybody's luck begins to run out. Lengel comes in from haggling with a truck full of cabbages on the lot and is about to scuttle into that door marked MANAGER behind which he hides all day when the girls touch his eye. Lengel's pretty dreary, teaches Sunday school and the rest, but he doesn't miss that much. He comes over and says, "Girls, this isn't the beach."</p>
<p>Queenie blushes, though maybe it's just a brush of sunburn I was noticing for the first time, now that she was so close. "My mother asked me to pick up a jar of herring snacks." Her voice kind of startled me, the way voices do when you see the people first, coming out so flat and dumb yet kind of tony, too, the way it ticked over "pick up" and "snacks." All of a sudden I slid right down her voice into her living room. Her father and the other men were standing around in ice-cream coats and bow ties and the women were in sandals picking up herring snacks on toothpicks off a big plate and they were all holding drinks the color of water with olives and sprigs of mint in them. When my parents have somebody over they get lemonade and if it's a real racy affair Schlitz in tall glasses with "They'll Do It Every Time" cartoons stencilled on.</p>
<p>"That's all right," Lengel said. "But this isn't the beach." His repeating this struck me as funny, as if it hadjust occurred to him, and he had been thinking all these years the A &amp; P was a great big dune and he was the head lifeguard. He didn't like my smiling -- -as I say he doesn't miss much -- but he concentrates on giving the girls that sad Sunday- school-superintendent stare.</p>
<p>Queenie's blush is no sunburn now, and the plump one in plaid, that I liked better from the back -- a really sweet can -- pipes up, "We weren't doing any shopping. We just came in for the one thing."</p>
<p>"That makes no difference," Lengel tells her, and I could see from the way his eyes went that he hadn't noticed she was wearing a two-piece before. "We want you decently dressed when you come in here."</p>
<p>"We are decent," Queenie says suddenly, her lower lip pushing, getting sore now that she remembers her place, a place from which the crowd that runs the A &amp; P must look pretty crummy. Fancy Herring Snacks flashed in her very blue eyes.</p>
<p>"Girls, I don't want to argue with you. After this come in here with your shoulders covered. It's our policy." He turns his back. That's policy for you. Policy is what the kingpins want. What the others want is juvenile delinquency.</p>
<p>All this while, the customers had been showing up with their carts but, you know, sheep, seeing a scene, they had all bunched up on Stokesie, who shook open a paper bag as gently as peeling a peach, not wanting to miss a word. I could feel in the silence everybody getting nervous, most of all Lengel, who asks me, "Sammy, have you rung up this purchase?"</p>
<p>I thought and said "No" but it wasn't about that I was thinking. I go through the punches, 4, 9, GROC, TOT -- it's more complicated than you think, and after you do it often enough, it begins to make a lttle song, that you hear words to, in my case "Hello <em>(bing)</em> there, you <em>(gung)</em> hap-py pee-pul <em>(splat)</em>"-the splat being the drawer flying out. I uncrease the bill, tenderly as you may imagine, it just having come from between the two smoothest scoops of vanilla I had ever known were there, and pass a half and a penny into her narrow pink palm, and nestle the herrings in a bag and twist its neck and hand it over, all the time thinking.</p>
<p>The girls, and who'd blame them, are in a hurry to get out, so I say "I quit" to Lengel quick enough for them to hear, hoping they'll stop and watch me, their unsuspected hero. They keep right on going, into the electric eye; the door flies open and they flicker across the lot to their car, Queenie and Plaid and Big Tall Goony-Goony (not that as raw material she was so bad), leaving me with Lengel and a kink in his eyebrow.</p>
<p>"Did you say something, Sammy?"</p>
<p>"I said I quit."</p>
<p>"I thought you did."</p>
<p>"You didn't have to embarrass them."</p>
<p>"It was they who were embarrassing us."</p>
<p>I started to say something that came out "Fiddle-de-doo." It's a saying of my grand- mother's, and I know she would have been pleased.</p>
<p>"I don't think you know what you're saying," Lengel said.</p>
<p>"I know you don't," I said. "But I do." I pull the bow at the back of my apron and start shrugging it off my shoulders. A couple customers that had been heading for my slot begin to knock against each other, like scared pigs in a chute.</p>
<p>Lengel sighs and begins to look very patient and old and gray. He's been a friend of my parents for years. "Sammy, you don't want to do this to your Mom and Dad," he tells me. It's true, I don't. But it seems to me that once you begin a gesture it's fatal not to go through with it. I fold the apron, "Sammy" stitched in red on the pocket, and put it on the counter, and drop the bow tie on top of it. The bow tie is theirs, if you've ever wondered. "You'll feel this for the rest of your life," Lengel says, and I know that's true, too, but remembering how he made that pretty girl blush makes me so scrunchy inside I punch the No Sale tab and the machine whirs "pee-pul" and the drawer splats out. One advantage to this scene taking place in summer, I can follow this up with a clean exit, there's no fumbling around getting your coat and galoshes, I just saunter into the electric eye in my white shirt that my mother ironed the night before, and the door heaves itself open, and outside the sunshine is skating around on the asphalt.</p>
<p>I look around for my girls, but they're gone, of course. There wasn't anybody but some young married screaming with her children about some candy they didn't get by the door of a powder-blue Falcon station wagon. Looking back in the big windows, over the bags of peat moss and aluminum lawn furniture stacked on the pavement, I could see Lengel in my place in the slot, checking the sheep through. His face was dark gray and his back stiff, as if he'djust had an injection of iron, and my stomach kind of fell as I felt how hard the world was going to be to me hereafter.</p>]
