@ohenryTLL = %Q[<p>In a little district west of Washington Square the streets have run crazy and broken themselves into small strips called "places." These "places" make strange angles and curves. One street crosses itself a time or two. An artist once discovered a valuable possibility in this street. Suppose a collector with a bill for paints, paper and canvas should, in traversing this route, suddenly meet himself coming back, without a cent having been paid on account!</p>
<p>So, to quaint old Greenwich Village the art people soon came prowling, hunting for north windows and eighteenth-century gables and Dutch attics and low rents. Then they imported some pewter mugs and a chafing dish or two from Sixth Avenue, and became a "colony."</p>
<p>At the top of a squatty, three story brick Sue and Johnsy had their studio. "Johnsy" was familiar for Joanna. One was from Maine; the other from California. They had met at the <em>table d'hote</em> of an Eighth Street "Delmonico's," and found their tastes in art, chicory salad and bishop sleeves so congenial that the studio resulted.</p>
<p>That was in May. In November a cold, unseen stranger, whom the doctors called Pneumonia, stalked about the colony, touching one here and there with his icy fingers. Over on the east side this ravager strode boldly, smiting his victims by scores, but his feet trod slowly through the maze of the narrow and moss-grown "places."</p>
<p>Mr. Pneumonia was not what you would call a chivalric old gentleman. A mite of a little woman with blood thinned by California zephyrs was hardly fair game for the red-fisted, short breathed old duffer. But Johnsy he smote; and she lay scarcely moving, on her painted iron bedstead, looking through the small Dutch window-panes at the blank side of the next brick house.</p>
<p>One morning the busy doctor invited Sue into the hallway with a shaggy, gray eyebrow.</p>
<p>"She has one chance in-let us say, ten," he said, as he shook down the mercury in his clinical thermometer. "And that chance is for her to want to live. This way people have of lining-up on the side of the undertaker makes the entire pharmacopoeia look silly. Your little lady has made up her mind that she's not going to get well. Has she anything on her mind?"</p>
<p>"She-she wanted to paint the Bay of Naples some day," said Sue.</p>
<p>"Paint?-bosh! Has she anything on her mind worth thinking about twice-a man, for instance?"</p>
<p>"A man?" said Sue, with a jew's-harp twang in her voice. "Is a man worth-but, no, doctor; there is nothing of the kind."</p>
<p>(1/4/09)</p>
<p>"Well, it is the weakness, then," said the doctor. "I will do all that science, so far as it may filter through my efforts, can accomplish. But whenever my patient begins to count the carriages in her funeral procession I subtract 50 per cent. from the curative power of medicines. If you will get her to ask one question about the new winter styles in cloak sleeves I will promise you a one-in-five chance for her, instead of ten."</p>
<p>After the doctor had gone Sue went into the workroom and cried a Japanese napkin to a pulp. Then she swaggered into Johnsy's room with her drawing board, whistling ragtime.</p>
<p>Johnsy, lay, scarcely making a ripple under the bedclothes, with her face toward the window. Sue stopped whistling, thinking she was asleep.</p>
<p>She arranged her board and began a pen and ink drawing to illustrate a magazine story. Young artists must pave their way to Art by drawing pictures for magazine stories that young authors write to pave their way to literature.</p>
<p>As Sue was sketching a pair of elegant horseshow riding trousers a monocle on the figure of the hero, an Idaho cowboy, she heard a low sound, several times repeated. She went quickly to the bedside.</p>
<p>Johnsy's eyes were open wide. She was looking out the window and counting-counting backward.</p>
<p>"Twelve," she said, and a little later "eleven"; and then "ten," and "nine"; and then "eight" and "seven," almost together.</p>
<p>Sue looked solicitously out the window. What was there to count? There was only a bare, dreary yard to be seen, and the blank side of the brick house twenty feet away. An old, old ivy vine, gnarled and decayed at the roots, climbed half way up the brick wall. The cold breath of autumn had stricken its leaves from the vine until its skeleton branches clung, almost bare, to the crumbling bricks.</p>
<p>"What is it, dear? Tell you Sudie."</p>
<p>"Leaves. On the ivy vine. When the last one falls I must go, too. I've known that for three days. Didn't the doctor tell you?"</p>
<p>"Oh, I never heard of such nonsense," complained Sue, with magnificent scorn. "What have old ivy leaves to do with your getting well? And you used to love that vine, so, you naughty girl. Don't be a goosey. Why, the doctor told me this morning that your chances for getting well real soon were-let's see exactly what he said-he said the chances were ten to one! Why that's almost as good a chance as we have in New York when we ride on the street cars or walk past a new building. Try to take some broth now, and let Sudie go back to her drawing, so she can sell the editor man with it, and buy port wine for her sick child, and pork chops for her greedy self."</p>
<p>"You needn't get any more wine," said Johnsy, keeping her eyes fixed on the window. "There goes another. No, I don't want any broth. That leaves just four. I want to see the last one fall before it gets dark. Then I'll go too."</p>
<p>"Johnsy, dear," said Sue, bending over her, "will you promise me to keep your eyes closed, and not look out the window until I am done working? I must hand those drawings in by to-morrow. I need the light, or I could draw the shade down."</p>
<p>"Couldn't you draw in the other room?" asked Johnsy, coldly.</p>
<p>"I'd rather be here by you," said Sue. "Besides, I don't want you to keep looking at those silly ivy leaves."</p>
<p>"Tell me as soon as you have finished," said Johnsy, closing her eyes, and lying white and still as a fallen statue, "because I want to see the last one fall. I'm tired of waiting. I'm tired of thinking. I want to turn loose my hold on everything, and go sailing down, down, just like one of those poor, tired leaves."</p>
<p>"Try to sleep," said Sue. "I must call Behrman up to be my model for the old hermit miner. I'll not be gone a minute. Don't try to move 'til I come back."</p>
<p>Old Behrman was a painter who lived on the ground floor beneath them. He was past sixty and had a Michael Angelo's Moses beard curling down from the head of a satyr along the body of an imp. Behrman was a failure in art. Forty years he had wielded the brush without getting near enough to touch the hem of his Mistress's robe. He had been always about to paint a masterpiece, but had never yet begun it. For several years he had painted nothing except now and then a daub in the line of commerce or advertising. He earned a little by serving as a model to those young artists in the colony who could not pay the price of a professional. He drank gin to excess, and still talked of his coming masterpiece. For the rest he was a fierce little old man, who scoffed terribly at the softness in any one, and who regarded himself as especial mastiff-in-waiting to protect the two young artists in the studio above.</p>
<p>Sue found Behrman smelling strongly of juniper berries in his dimly lighted den below. In one corner was a blank canvas on an easel that had been waiting there for twenty-five years to receive the first line of the masterpiece. She told him of Johnsy's fancy, and how she feared she would, indeed light and fragile as a leaf herself, float away, when her slight hold upon the world grew weaker.</p>
<p>Old Behrman, with his red eyes plainly streaming, shouted his contempt and derision for such idiotic imaginings.</p>
<p>"Vass!" he cried. "Is dere people in de world mit der foolishness to die because leafs dey drop off from a confounded vine? I haf not heard of such a thing. No, I will not bose as a model for you fool hermit-dunder-head. Vy do you allow dot silly pusiness to come in der brain aof her? Ach, dot poor lettle Miss Yohnsy."</p>
<p>"She is very ill and weak," said Sue, "and the fever has left her mind morbid and full of strange fancies. Very well, Mr. Behrman, if you do not care to pose for me, you needn't. But I think you are a horrid old-old flibbertigibbet."</p>
<p>"You are just like a woman!" yelled Behrman. "Who said I will not bose? Go on. I come mit you. For half and hour I haf peen trying to say dot I am ready to bose. Gott! dis is not any blace in which one so gooot as Miss Yohnsy shall lie sick. Some day I vill baint a masterpiece, and ve shall all go away. Gott! yes."</p>
<p>Johnsy was sleeping when they went upstairs. She pulled the shade down to the window-sill, and motioned Behrman into the other room. In there they peered out the window fearfully at the ivy vine. Then they looked at each other for a moment with out speaking. A persistent, cold rain was falling, mingled with snow. Behrman, in his old blue shirt, took his seat as the hermit miner on an upturned kettle for a rock.</p>
<p>When Sue awoke from and hour's sleep the next morning she found Johnsy with dull, wide-open eyes staring at the drawn green shade.</p>
<p>"Pull it up; I want to see," she ordered, in a whisper.</p>
<p>Wearily Sue obeyed.</p>
<p>But Loa! after the beating rain and fierce gusts of wind that had endured through the livelong night, there yet stood out against the brick wall one ivy leaf. It was the last on the vine. Still dark green near its stem, but with its serrated edges tinted with the yellow of dissolution and decay, it hung bravely from a branch some twenty feet above the ground.</p>
<p>"It is the last one," said Johnsy. "I thought it would surely fall during the night. I heard the wind. It will fall to-day, and I shall die at the same time."</p>
<p>"Dear, dear!" said Sue, leaning her worn face down to the pillow, "think of me, if you won't think of yourself. What would I do?"</p>
<p>But Johnsy did not answer. The lonesomest thing in all the world is a soul when it is making ready to go on its mysterious, far journey. The fancy seemed to posses her more strongly as one by one the ties that bound her to friendship and to earth were loosed.</p>
<p>The day wore away, and even though the twilight they could see the lone ivy leaf clinging to its stem against the wall. And then, with the coming of the night the north wind was again down from the low Dutch eaves.</p>
<p>When it was light enough Johnsy, the merciless, commanded that the shade be raised.</p>
<p>The ivy leaf was still there.</p>
<p>Johnsy lay for a long time looking at it. And then she called to Sue, who was stirring her chicken broth over the gas stove.</p>
<p>"I've been a bad girl, Sudie," said Johnsy. "Something has made that last leaf stay there to show me how wicked I was. It is a sin to want to die. You may bring me a little broth now, and some milk with a little port in it, and-no; bring me a hand-mirror first, and then pack some pillows about me, and I will sit up and watch you cook."</p>
<p>An hour later she said:</p>
<p>"Sudie, some day I hope to paint the Bay of Naples."</p>
<p>The doctor came in the afternoon, and Sue had an excuse to go into the hallway as he left.</p>
<p>"Even chances," said the doctor, taking Sue's thin shaking hand in his. "With good nursing you'll win. And now I must see another case I have downstairs. Behrman, his name is-some kind of artist, I believe. Pneumonia, too. He is old, weak man, and the attack is acute. There is no hope for him; but he goes to the hospital today to be made more comfortable."</p>
<p>The next day the doctor said to Sue: "She's out of danger. You've won. Nutrition and care now-that's all."</p>
<p>And that afternoon Sue came to the bed where Johnsy lay, contentedly knitting a very blue and very useless woollen shoulder scarf, and put one arm around her, pillows and all.</p>
<p>"I have something to tell you, white mouse," she said. "Mr. Behrman died of pneumonia today in the hospital. He was ill only two days. The janitor found him on the morning of the first day in his room downstairs helpless with pain. His shoes and clothing were wet through and icy cold. They couldn't imagine where he had been on such a dreadful night. And then they found a lantern, still lighted, and a ladder that had been dragged from its place, and some scattered brushes, and a palette with green and yellow colors mixed on it, and-look out the window, dear, at the last ivy leaf on the wall. Didn't you wonder why it never fluttered or moved when the wind blew? Ah, darling, it's Behrman's masterpiece-he painted it there the night the last leaf fell."</p>
<center>THE END</center>]
