@ohenryTRORC = %Q[<p>It looked like a good thing: but wait till I tell you. We were down South, in Alabama--Bill Driscoll and myself-when this kidnapping idea struck us. It was, as Bill afterward expressed it, 'during a moment of temporary mental apparition'; but we didn't find that out till later.</p>
<p>There was a town down there, as flat as a flannel-cake, and called Summit, of course. It contained inhabitants of as undeleterious and self-satisfied a class of peasantry as ever clustered around a Maypole.</p>
<p>Bill and me had a joint capital of about six hundred dollars, and we needed just two thousand dollars more to pull off a fraudulent town-lot scheme in Western Illinois with. We talked it over on the front steps of the hotel. Philoprogenitiveness, says we, is strong in semi-rural communities therefore, and for other reasons, a kidnapping project ought to do better there than in the radius of newspapers that send reporters out in plain clothes to stir up talk about such things. We knew that Summit couldn't get after us with anything stronger than constables and, maybe, some lackadaisical bloodhounds and a diatribe or two in the <em>Weekly Farmers' Budget.</em> So, it looked good.</p>
<p>We selected for our victim the only child of a prominent citizen named Ebenezer Dorset. The father was respectable and tight, a mortgage fancier and a stern, upright collection-plate passer and forecloser. The kid was a boy of ten, with bas-relief freckles, and hair the colour of the cover of the magazine you buy at the news-stand when you want to catch a train. Bill and me figured that Ebenezer would melt down for a ransom of two thousand dollars to a cent. But wait till I tell you.</p>
<p>About two miles from Summit was a little mountain, covered with a dense cedar brake. On the rear elevation of this mountain was a cave. There we stored provisions.</p>
<p>One evening after sundown, we drove in a buggy past old Dorset's house. The kid was in the street, throwing rocks at a kitten on the opposite fence.</p>
<p>'Hey, little boy!' says Bill, 'would you like to have a bag of candy and a nice ride?'</p>
<p>The boy catches Bill neatly in the eye with a piece of brick.</p>
<p>'That will cost the old man an extra five hundred dollars,' says Bill, climbing over the wheel.</p>
<p>That boy put up a fight like a welter-weight cinnamon bear; but, at last, we got him down in the bottom of the buggy and drove away. We took him up to the cave, and I hitched the horse in the cedar brake. After dark I drove the buggy to the little village, three miles away, where we had hired it, and walked back to the mountain.</p>
<p>Bill was pasting court-plaster over the scratches and bruises on his features. There was a fire burning behind the big rock at the entrance of the cave, and the boy was watching a pot of boiling coffee, with two buzzard tailfeathers stuck in his red hair. He points a stick at me when I come up, and says:</p>
<p>'Ha! cursed paleface, do you dare to enter the camp of Red Chief, the terror of the plains?'</p>
<p>'He's all right now,' says Bill, rolling up his trousers and examining some bruises on his shins. 'We're playing Indian. We're making Buffalo Bill's show look like magic-lantern views of Palestine in the town hall. I'm Old Hank, the Trapper, Red Chief's captive, and I'm to be scalped at daybreak. By Geronimo! that kid can kick hard.'</p>
<p>Yes, sir, that boy seemed to be having the time of his life. The fun of camping out in a cave had made him forget that he was a captive himself. He immediately christened me Snake-eye, the Spy, and announced that, when his braves returned from the warpath, I was to be broiled at the stake at the rising of the sun.</p>
<p>Then we had supper; and he filled his mouth full of bacon and bread and gravy, and began to talk. He made a during-dinner speech something like this:</p>
<p>'I like this fine. I never camped out before; but I had a pet 'possum once, and I was nine last birthday. I hate to go to school. Rats ate up sixteen of Jimmy Talbot's aunt's speckled hen's eggs. Are there any real Indians in these woods? I want some more gravy. Does the trees moving make the wind blow? We had five puppies. What makes your nose so red, Hank? My father has lots of money. Are the stars hot? I whipped Ed Walker twice, Saturday. I don't like girls. You dassent catch toads unless with a string. Do oxen make any noise? Why are oranges round? Have you got beds to sleep on in this cave? Amos Murray has got six toes. A parrot can talk, but a monkey or a fish can't. How many does it take to make twelve?'</p>
<p>Every few minutes he would remember that he was a pesky redskin, and pick up his stick rifle and tiptoe to the mouth of the cave to rubber for the scouts of the hated paleface. Now and then he would let out a warwhoop that made Old Hank the Trapper, shiver. That boy had Bill terrorized from the start.</p>
<p>'Red Chief,' says I to the kid, 'would you like to go home?'</p>
<p>'Aw, what for?' says he. 'I don't have any fun at home. I hate to go to school. I like to camp out. You won't take me back home again, Snake-eye, will you?'</p>
<p>'Not right away,' says I. 'We'll stay here in the cave a while.'</p>
<p>'All right!' says he. 'That'll be fine. I never had such fun in all my life.'</p>
<p>We went to bed about eleven o'clock. We spread down some wide blankets and quilts and put Red Chief between us. We weren't afraid he'd run away. He kept us awake for three hours, jumping up and reaching for his rifle and screeching: 'Hist! pard,' in mine and Bill's ears, as the fancied crackle of a twig or the rustle of a leaf revealed to his young imagination the stealthy approach of the outlaw band. At last, I fell into a troubled sleep, and dreamed that I had been kidnapped and chained to a tree by a ferocious pirate with red hair.</p>
<p>Just at daybreak, I was awakened by a series of awful screams from Bill. They weren't yells, or howls, or shouts, or whoops, or yawps, such as you'd expect from a manly set of vocal organs--they were simply indecent, terrifying, humiliating screams, such as women emit when they see ghosts or caterpillars. It's an awful thing to hear a strong, desperate, fat man scream incontinently in a cave at daybreak.</p>
<p>I jumped up to see what the matter was. Red Chief was sitting on Bill's chest, with one hand twined in Bill's hair. In the other he had the sharp case-knife we used for slicing bacon; and he was industriously and realistically trying to take Bill's scalp, according to the sentence that had been pronounced upon him the evening before.</p>
<p>I got the knife away from the kid and made him lie down again. But, from that moment, Bill's spirit was broken. He laid down on his side of the bed, but he never closed an eye again in sleep as long as that boy was with us. I dozed off for a while, but along toward sun-up I remembered that Red Chief had said I was to be burned at the stake at the rising of the sun. I wasn't nervous or afraid; but I sat up and lit my pipe and leaned against a rock.</p>
<p>'What you getting up so soon for, Sam?' asked Bill.</p>
<p>'Me?' says I. 'Oh, I got a kind of a pain in my shoulder. I thought sitting up would rest it.'</p>
<p>'You're a liar!' says Bill. 'You're afraid. You was to be burned at sunrise, and you was afraid he'd do it. And he would, too, if he could find a match. Ain't it awful, Sam? Do you think anybody will pay out money to get a little imp like that back home?'</p>
<p>'Sure,' said I. 'A rowdy kid like that is just the kind that parents dote on. Now, you and the Chief get up and cook breakfast, while I go up on the top of this mountain and reconnoitre.'</p>
<p>I went up on the peak of the little mountain and ran my eye over the contiguous vicinity. Over toward Summit I expected to see the sturdy yeomanry of the village armed with scythes and pitchforks beating the countryside for the dastardly kidnappers. But what I saw was a peaceful landscape dotted with one man ploughing with a dun mule. Nobody was dragging the creek; no couriers dashed hither and yon, bringing tidings of no news to the distracted parents. There was a sylvan attitude of somnolent sleepiness pervading that section of the external outward surface of Alabama that lay exposed to my view. 'Perhaps,' says I to myself, 'it has not yet been discovered that the wolves have borne away the tender lambkin from the fold. Heaven help the wolves!' says I, and I went down the mountain to breakfast.</p>
<p>When I got to the cave I found Bill backed up against the side of it, breathing hard, and the boy threatening to smash him with a rock half as big as a cocoanut.</p>
<p>'He put a red-hot boiled potato down my back,' explained Bill, 'and then mashed it with his foot; and I boxed his ears. Have you got a gun about you, Sam?'</p>
<p>I took the rock away from the boy and kind of patched up the argument. 'I'll fix you,' says the kid to Bill. 'No man ever yet struck the Red Chief but what he got paid for it. You better beware!'</p>
<p>After breakfast the kid takes a piece of leather with strings wrapped around it out of his pocket and goes outside the cave unwinding it.</p>
<p>'What's he up to now?' says Bill, anxiously. 'You don't think he'll run away, do you, Sam?'</p>
<p>'No fear of it,' says I. 'He don't seem to be much of a home body. But we've got to fix up some plan about the ransom. There don't seem to be much excitement around Summit on account of his disappearance; but maybe they haven't realized yet that he's gone. His folks may think he's spending the night with Aunt Jane or one of the neighbours. Anyhow, he'll be missed to-day. To-night we must get a message to his father demanding the two thousand dollars for his return.'</p>
<p>Just then we heard a kind of war-whoop, such as David might have emitted when he knocked out the champion Goliath. It was a sling that Red Chief had pulled out of his pocket, and he was whirling it around his head.</p>
<p>I dodged, and heard a heavy thud and a kind of a sigh from Bill, like a horse gives out when you take his saddle off. A niggerhead rock the size of an egg had caught Bill just behind his left ear. He loosened himself all over and fell in the fire across the frying pan of hot water for washing the dishes. I dragged him out and poured cold water on his head for half an hour.</p>
<p>By and by, Bill sits up and feels behind his ear and says: 'Sam, do you know who my favourite Biblical character is?'</p>
<p>'Take it easy,' says I. 'You'll come to your senses presently.'</p>
<p>'King Herod,' says he. 'You won't go away and leave me here alone, will you, Sam?'</p>
<p>I went out and caught that boy and shook him until his freckles rattled.</p>
<p>'If you don't behave,' says I, 'I'll take you straight home. Now, are you going to be good, or not?'</p>
<p>'I was only funning,' says he sullenly. 'I didn't mean to hurt Old Hank. But what did he hit me for? I'll behave, Snake-eye, if you won't send me home, and if you'll let me play the Black Scout to-day.'</p>
<p>'I don't know the game,' says I. 'That's for you and Mr. Bill to decide. He's your playmate for the day. I'm going away for a while, on business. Now, you come in and make friends with him and say you are sorry for hurting him, or home you go, at once.'</p>
<p>I made him and Bill shake hands, and then I took Bill aside and told him I was going to Poplar Cove, a little village three miles from the cave, and find out what I could about how the kidnapping had been regarded in Summit. Also, I thought it best to send a peremptory letter to old man Dorset that day, demanding the ransom and dictating how it should be paid.</p>
<p>'You know, Sam,' says Bill, 'I've stood by you without batting an eye in earthquakes, fire and flood--in poker games, dynamite outrages, police raids, train robberies and cyclones. I never lost my nerve yet till we kidnapped that two-legged skyrocket of a kid. He's got me going. You won't leave me long with him, will you, Sam?'</p>
<p>'I'll be back some time this afternoon,' says I. 'You must keep the boy amused and quiet till I return. And now we'll write the letter to old Dorset.'</p>
<p>Bill and I got paper and pencil and worked on the letter while Red Chief, with a blanket wrapped around him, strutted up and down, guarding the mouth of the cave. Bill begged me tearfully to make the ransom fifteen hundred dollars instead of two thousand. 'I ain't attempting,' says he, 'to decry the celebrated moral aspect of parental affection, but we're dealing with humans, and it ain't human for anybody to give up two thousand dollars for that forty-pound chunk of freckled wildcat. I'm willing to take a chance at fifteen hundred dollars. You can charge the difference up to me.'</p>
<p>So, to relieve Bill, I acceded, and we collaborated a letter that ran this way:</p>
<blockquote>
<p>Ebenezer Dorset, Esq.:</p>
<p>We have your boy concealed in a place far from Summit. It is useless for you or the most skilful detectives to attempt to find him. Absolutely, the only terms on which you can have him restored to you are these: We demand fifteen hundred dollars in large bills for his return; the money to be left at midnight to-night at the same spot and in the same box as your reply--as hereinafter described. If you agree to these terms, send your answer in writing by a solitary messenger to-night at half-past eight o'clock. After crossing Owl Creek, on the road to Poplar Cove, there are three large trees about a hundred yards apart, close to the fence of the wheat field on the right-hand side. At the bottom of the fence-post, opposite the third tree, will be found a small pasteboard box.</p>
<p>The messenger will place the answer in this box and return immediately to Summit.</p>
<p>If you attempt any treachery or fail to comply with our demand as stated, you will never see your boy again.</p>
<p>If you pay the money as demanded, he will be returned to you safe and well within three hours. These terms are final, and if you do not accede to them no further communication will be attempted.</p>
<p>TWO DESPERATE MEN.</p>
</blockquote>
<p>I addressed this letter to Dorset, and put it in my pocket. As I was about to start, the kid comes up to me and says:</p>
<p>'Aw, Snake-eye, you said I could play the Black Scout while you was gone.'</p>
<p>'Play it, of course,' says I. 'Mr. Bill will play with you. What kind of a game is it?'</p>
<p>'I'm the Black Scout,' says Red Chief, 'and I have to ride to the stockade to warn the settlers that the Indians are coming. I 'm tired of playing Indian myself. I want to be the Black Scout.'</p>
<p>'All right,' says I. 'It sounds harmless to me. I guess Mr. Bill will help you foil the pesky savages.'</p>
<p>'What am I to do?' asks Bill, looking at the kid suspiciously.</p>
<p>'You are the hoss,' says Black Scout. 'Get down on your hands and knees. How can I ride to the stockade without a hoss?'</p>
<p>'You'd better keep him interested,' said I, 'till we get the scheme going. Loosen up.'</p>
<p>Bill gets down on his all fours, and a look comes in his eye like a rabbit's when you catch it in a trap.</p>
<p>' How far is it to the stockade, kid? ' he asks, in a husky manner of voice.</p>
<p>'Ninety miles,' says the Black Scout. 'And you have to hump yourself to get there on time. Whoa, now!'</p>
<p>The Black Scout jumps on Bill's back and digs his heels in his side.</p>
<p>'For Heaven's sake,' says Bill, 'hurry back, Sam, as soon as you can. I wish we hadn't made the ransom more than a thousand. Say, you quit kicking me or I '11 get up and warm you good.'</p>
<p>I walked over to Poplar Cove and sat around the postoffice and store, talking with the chawbacons that came in to trade. One whiskerand says that he hears Summit is all upset on account of Elder Ebenezer Dorset's boy having been lost or stolen. That was all I wanted to know. I bought some smoking tobacco, referred casually to the price of black-eyed peas, posted my letter surreptitiously and came away. The postmaster said the mail-carrier would come by in an hour to take the mail on to Summit.</p>
<p>When I got back to the cave Bill and the boy were not to be found. I explored the vicinity of the cave, and risked a yodel or two, but there was no response.</p>
<p>So I lighted my pipe and sat down on a mossy bank to await developments.</p>
<p>In about half an hour I heard the bushes rustle, and Bill wabbled out into the little glade in front of the cave. Behind him was the kid, stepping softly like a scout, with a broad grin on his face. Bill stopped, took off his hat and wiped his face with a red handkerchief. The kid stopped about eight feet behind him.</p>
<p>'Sam,' says Bill, 'I suppose you'll think I'm a renegade, but I couldn't help it. I'm a grown person with masculine proclivities and habits of self-defence, but there is a time when all systems of egotism and predominance fail. The boy is gone. I have sent him home. All is off. There was martyrs in old times,' goes on Bill, 'that suffered death rather than give up the particular graft they enjoyed. None of 'em ever was subjugated to such supernatural tortures as I have been. I tried to be faithful to our articles of depredation; but there came a limit.'</p>
<p>'What's the trouble, Bill?' I asks him.</p>
<p>'I was rode,' says Bill, 'the ninety miles to the stockade, not barring an inch. Then, when the settlers was rescued, I was given oats. Sand ain't a palatable substitute. And then, for an hour I had to try to explain to him why there was nothin' in holes, how a road can run both ways and what makes the grass green. I tell you, Sam, a human can only stand so much. I takes him by the neck of his clothes and drags him down the mountain. On the way he kicks my legs black-and-blue from the knees down; and I've got two or three bites on my thumb and hand cauterized.</p>
<p>'But he's gone'--continues Bill--'gone home. I showed him the road to Summit and kicked him about eight feet nearer there at one kick. I'm sorry we lose the ransom; but it was either that or Bill Driscoll to the madhouse.'</p>
<p>Bill is puffing and blowing, but there is a look of ineffable peace and growing content on his rose-pink features.</p>
<p>'Bill,' says I, 'there isn't any heart disease in your family, is there?'</p>
<p>'No,' says Bill, 'nothing chronic except malaria and accidents. Why?'</p>
<p>'Then you might turn around,' says I, 'and have a look behind you.'</p>
<p>Bill turns and sees the boy, and loses his complexion and sits down plump on the ground and begins to pluck aimlessly at grass and little sticks. For an hour I was afraid for his mind. And then I told him that my scheme was to put the whole job through immediately and that we would get the ransom and be off with it by midnight if old Dorset fell in with our proposition. So Bill braced up enough to give the kid a weak sort of a smile and a promise to play the Russian in a Japanese war with him as soon as he felt a little better.</p>
<p>I had a scheme for collecting that ransom without danger of being caught by counterplots that ought to commend itself to professional kidnappers. The tree under which the answer was to be left--and the money later on--was close to the road fence with big, bare fields on all sides. If a gang of constables should be watching for any one to come for the note they could see him a long way off crossing the fields or in the road. But no, sirree! At half-past eight I was up in that tree as well hidden as a tree toad, waiting for the messenger to arrive.</p>
<p>Exactly on time, a half-grown boy rides up the road on a bicycle, locates the pasteboard box at the foot of the fencepost, slips a folded piece of paper into it and pedals away again back toward Summit.</p>
<p>I waited an hour and then concluded the thing was square. I slid down the tree, got the note, slipped along the fence till I struck the woods, and was back at the cave in another half an hour. I opened the note, got near the lantern and read it to Bill. It was written with a pen in a crabbed hand, and the sum and substance of it was this:</p>
<blockquote>
<p>Two Desperate Men.</p>
<p>Gentlemen: I received your letter to-day by post, in regard to the ransom you ask for the return of my son. I think you are a little high in your demands, and I hereby make you a counter-proposition, which I am inclined to believe you will accept. You bring Johnny home and pay me two hundred and fifty dollars in cash, and I agree to take him off your hands. You had better come at night, for the neighbours believe he is lost, and I couldn't be responsible for what they would do to anybody they saw bringing him back.</p>
<p>Very respectfully,<br />EBENEZER DORSET.</p>
</blockquote>
<p>'Great pirates of Penzance!' says I; 'of all the impudent--'</p>
<p>But I glanced at Bill, and hesitated. He had the most appealing look in his eyes I ever saw on the face of a dumb or a talking brute.</p>
<p>'Sam,' says he, 'what's two hundred and fifty dollars, after all? We've got the money. One more night of this kid will send me to a bed in Bedlam. Besides being a thorough gentleman, I think Mr. Dorset is a spendthrift for making us such a liberal offer. You ain't going to let the chance go, are you?'</p>
<p>'Tell you the truth, Bill,' says I, 'this little he ewe lamb has somewhat got on my nerves too. We'll take him home, pay the ransom and make our get-away.'</p>
<p>We took him home that night. We got him to go by telling him that his father had bought a silver-mounted rifle and a pair of moccasins for him, and we were going to hunt bears the next day.</p>
<p>It was just twelve o'clock when we knocked at Ebenezer's front door. Just at the moment when I should have been abstracting the fifteen hundred dollars from the box under the tree, according to the original proposition, Bill was counting out two hundred and fifty dollars into Dorset's hand.</p>
<p>When the kid found out we were going to leave him at home he started up a howl like a calliope and fastened himself as tight as a leech to Bill's leg. His father peeled him away gradually, like a porous plaster.</p>
<p>'How long can you hold him?' asks Bill.</p>
<p>'I'm not as strong as I used to be,' says old Dorset, 'but I think I can promise you ten minutes.'</p>
<p>'Enough,' says Bill. 'In ten minutes I shall cross the Central, Southern and Middle Western States, and be legging it trippingly for the Canadian border.'</p>
<p>And, as dark as it was, and as fat as Bill was, and as good a runner as I am, he was a good mile and a half out of summit before I could catch up with him.</p>]
