@skingCOTK_1 = %Q[<p>Burt turned the radio on too loud and didn't turn it down because they were on the verge of another argument and he didn't want it to happen. He was desperate for it not to happen.</p>
<p>Vicky said something. 'What?' he shouted. 'Turn it down! Do you want to break my eardrums? 'He bit down hard on what might have come through his mouth and turned it down. Vicky was fanning herself with her scarf even though the T-Bird was air-conditioned. 'Where are we, anyway?' -'Nebraska.' She gave him a cold, neutral look. 'Yes, Burt. I know we're in Nebraska, Burt. But where the hell are we?' 'You've got the road atlas. Look it up. Or can't you read?'</p>
<p>'Such wit. This is why we got off the turnpike. So we could look at three hundred miles of corn. And enjoy the wit and wisdom of Burt Robeson.'He was gripping the steering wheel so hard his knuckles were white. He decided he was holding it that tightly because if he loosened up, why, one of those hands might just fly off and hit the ex-Prom Queen beside him right in the chops. We 're saving our marriage, he told himself. Yes. We're doing it the same way us grunts went about saving villages in the war.</p>
<p>'Vicky,' he said carefully. 'I have driven fifteen hundred miles on turnpikes since we left Boston. I did all that driving myself because you refused to drive. Then -' -'I did not refuse!' Vicky said hotly. 'Justbecause I get migraines when I drive for a long time -'Then when I asked you if you'd navigate for me on some of the secondary roads, you said sure, Burt. Those were your exact words. Sure, Burt. Then -'Sometimes I wonder how I ever wound up married to you.'</p>
<p>'By saying two little words.' She stared at him for a moment, white-lipped, and then picked up the road atlas. She turned the pages savagely. It had been a mistake leaving the turnpike, Burt thought morosely. It was a shame, too, because up until then they had been doing pretty well, treating each other almost like human beings. It had sometimes seemed that this trip to the coast, ostensibly to see Vicky's brother and his wife but actually a last-ditch attempt to patch up their own marriage, was going to work.</p>
<p>But since they left the pike, it had been bad again. How bad? Well, terrible, actually. 'We left the turnpike at Hamburg, right?' -'Right.'</p>
<p>'There's nothing more until Gatlin,' she said. 'Twenty miles. Wide place in the road. Do you suppose we could stop there and get something to eat? Or does your almighty schedule say we have to go until two o'clock like we did yesterday?'</p>
<p>He took his eyes off the road to look at her. 'I've about had it, Vicky. As far as I'm concerned, we can turn right here and go home and see that<br />lawyer you wanted to talk to. Because this isn't working at -'</p>
<p>She had faced forward again, her expression stonily set. It suddenly turned to surprise and fear. 'Burt look out you're going to -'</p>
<p>He turned his attention back to the road just in time to see something vanish under the T-Bird's bumper. A moment later, while he was only beginning to switch from gas to brake, he felt something thump sickeningly under the front and then the back wheels. They were thrown forward as the car braked along the centre line, decelerating from fifty to zero along black skidmarks.</p>
<p>'A dog,' he said. 'Tell me it was a dog, Vicky.'</p>
<p>Her face was a pallid, cottage-cheese colour. 'A boy. A little boy. He just ran out of the corn and. . . congratulations, tiger.' She fumbled the car door open, leaned out, threw up.</p>
<p>Burt sat straight behind the T-Bird's wheel, hands still gripping it loosely. He was aware of nothing for a long time but the rich, dark smell of fertilizer. Then he saw that Vicky was gone and when he looked in the outside mirror he saw her stumbling clumsily back towards a heaped bundle that looked like a pile of rags. She was ordinarily a graceful woman but now her grace was gone, robbed.</p>
<p>It's manslaughter. That's what they call it. I took my eyes off the road. He turned the ignition off and got out. The wind rustled softly through the growing man-high corn, making a weird sound like respiration. Vicky was standing over the bundle of rags now, and he could hear her sobbing. He was halfway between the car and where she stood and something caught his eye on the left, a gaudy splash of red amid all the green, as bright as barn paint.</p>
<p>He stopped, looking directly into the corn. He found himself thinking (anything to untrack from those rags that were not rags) that it must have been a fantastically good growing season for corn. It grew close together, almost ready to bear. You could plunge into those neat, shaded rows and spend a day trying to find your way out again. But the neatness was broken here. Several tall cornstalks had been broken and leaned askew. And what was that further back in the shadows?</p>
<p>'Burt!' Vicky screamed at him. 'Don't you want to come see? So you can tell all your poker buddies what you bagged in Nebraska? Don't you' -'But the rest was lost in fresh sobs. Her shadow was puddled starkly around her feet. It was almost noon. Shade closed over him as he entered the corn. The red barn paint was blood. There was a low, somnolent buzz as flies lit, tasted, and buzzed off again . . . maybe to tell others. There was more blood on the leaves further in. Surely it couldn't have splattered this far? And then he was standing over the object he had seen from the road. He picked it up. The neatness of the rows was disturbed here. Several stalks were canted drunkenly, two of them had been broken clean off. The earth had been gouged. There was blood. The corn rustled. With a little shiver, he walked back to the road.</p>
<p>Vicky was having hysterics, screaming unintelligible words at him, crying, laughing. Who would have thought it could end in such a melodramatic way? He looked at her and saw he wasn't having an identity crisis or a difficult life transition or any of those trendy things.He hated her. He gave her a hard slap across the face.</p>
<p>She stopped short and put a hand against the reddening impression of his fingers. 'You'll go to jail, Burt,' she said solemnly. 'I don't think so,' he said, and put the suitcase he had found in the corn at her feet. 'What -?'</p>
<p>'I don't know. I guess it belonged to him.' He pointed to the sprawled, face-down body that lay in the road. No more than thirteen, from the look of him. The suitcase was old. The brown leather was battered and scuffed. Two hanks of clothesline had been wrapped around it and tied in large, clownish grannies. Vicky bent to undo one of them, saw, the blood greased into the knot, and withdrew.</p>
<p>Burt knelt and turned the body over gently. 'I don't want to look,' Vicky said, staring down helplessly anyway. And when the staring, sightless face flopped up to regard them, she screamed again. The boy's face was dirty, his expression a grimace of terror. His throat had been cut. Burt got up and put his arms around Vicky as she began to sway. 'Don't faint,' he said very quietly. 'Do you hear me, Vicky? Don't faint.' He repeated it over and over and at last she began to recover and held him tight. They might have been dancing, there on the noon-struck road with the boy's corpse at their feet.</p>
<p>'Vicky?' -'What?' Muffled against his shirt.</p>
<p>'Go back to the car and put the keys in your pocket. Get the blanket out of the back seat, and my rifle. Bring them here.' -'The rifle?'</p>
<p>'Someone cut his throat. Maybe whoever is watching us.' Her head jerked up and her wide eyes considered the corn. It marched away as far as the eye could see, undulating up and down small dips and rises of land. 'I imagine he's gone. But why take<br />chances? Go on. Do it.'</p>
<p>She walked stiltedly back to the car, her shadow following, a dark mascot who stuck close at this hour of the day. When she leaned into the back seat, Burt squatted beside the boy. White male, no distinguishing marks. Run over, yes, but the T-Bird hadn't cut the kid's throat. It had been cut raggedly and inefficiently - no army sergeant had shown the killer the finer points of hand-to-hand assassination -but the final effect had been deadly. He had either run or been pushed through the last thirty feet of corn, dead or mortally wounded. And Burt Robeson had run him down. If the boy had still been alive when the car hit him, his life had been cut short by thirty seconds at most.</p>
<p>Vicky tapped him on the shoulder and he jumped.</p>
<p>She was standing with the brown army blanket over her left arm, the cased pump shotgun in her right hand, her face averted. He took the blanket and spread it on the road. He rolled the body on to it. Vicky uttered a desperate little moan.</p>
<p>'You okay?' He looked up at her. 'Vicky?'</p>
<p>'Okay,' she said in a strangled voice. He flipped the sides of the blanket<br />over the body and scooped it up, hating the thick, dead weight of it. It tried to make a U in his arms and slither through his grasp. He clutched it tighter and they walked back to the T-Bird.</p>
<p>'Open the trunk,' he grunted.</p>
<p>The trunk was full of travel stuff, suitcases and souvenirs. Vicky shifted most of it into the back seat and Burt slipped the body into the made space and slammed the trunk lid down. A sigh of relief escaped him.</p>
<p>Vicky was standing by the driver's side door, still holding the cased rifle.</p>
<p>'Just put it in the back and get in.'</p>
<p>He looked at his watch and saw only fifteen minutes had passed. It seemed like hours. 'What about the suitcase?' she asked. He trotted back down the road to where it stood on the white line, like the focal point in an Impressionist painting. He picked it up by its tattered handle and paused for a moment. He had a strong sensation of being watched. It was a feeling he had read about in books, mostly cheap fiction, and he had always doubted its reality. Now he didn't. It was as if there were people in the corn, maybe a lot of them, coldly estimating whether the woman could get the gun out of the case and use it before they could grab him, drag him into the shady rows, cut his throat -Heart beating thickly, he ran back to the car, pulled the keys out of the trunk lock, and got in.</p>
<p>Vicky was crying again. Burt got them moving, and before a minute had passed, he could no longer pick out the spot where it had happened in the rear-view mirror.</p>
<p>'What did you say the next town was?' he asked.</p>
<p>'Oh.' She bent over the road atlas again. 'Gatlin. We should be there in ten minutes.' -'Does it look big enough to have a police station?'</p>
<p>'No. It's just a dot.' -'Maybe there's a constable.' They drove in silence for a while. They passed a silo on the left. Nothing else but corn. Nothing passed them going the other way, not even a farm truck.</p>
<p>'Have we passed anything since we got off the turnpike, Vicky?' She thought about it. 'A car and a tractor. At that intersection.' -'No, since we got on this road, Route 17.'</p>
<p>'No. I don't think we have.' Earlier this might have been the preface to some cutting remark. Now she only stared out of her half of the windshield at the unrolling road and the endless dotted line. 'Vicky? Could you open the suitcase?' -'Do you think it might matter?' -'Don't know. It might.'</p>
<p>While she picked at the knots (her face was set in a peculiar way - expressionless but tight-mouthed - that Burt remembered his mother wearing when she pulled the innards out of the Sunday chicken), Burt turned on the radio again.</p>
<p>The pop station they had been listening to was almost obliterated in static and Burt switched, running the red marker slowly down the dial. Farm reports. Buck Owens. Tammy Wynette. All distant, nearly distorted into babble. Then, near the end of the dial, one single word blared out of the speaker, so loud and clear that the lips which uttered it might have been directly beneath the grill of the dashboard speaker.</p>
<p>'ATONEMENT!' this voice bellowed. Burt made a surprised grunting sound. Vicky jumped.</p>
<p>'ONLY BY THE BLOOD OF THE LAMB ARE WE SAVED' the voice roared, and Burt hurriedly turned the sound down. This station was close, all right. So close that yes, there it was. Poking out of the corn at the horizon, a spidery red tripod against the blue. The radio tower.</p>
<p>'Atonement is the word, brothers 'n' sisters,' the voice told them, dropping to a more conversational pitch. In the background, off-mike, voices murmured amen. 'There's some that thinks it's okay to get out in the world, as if you could work and walk in the world without being smirched by the world. Now is that what the word of God teaches us?'</p>
<p>Off-mike but still loud: 'No!'</p>
<p>'HOLY JESUS!' the evangelist shouted, and now the words came in a powerful, pumping cadence, almost as compelling as a driving rock-and-roll beat: 'When they gonna know that way is death? When they gonna know that the wages of the world are paid on the other side? Huh? Huh? The Lord has said there's many mansions in His house. But there's no room for the fornicator. No room for the coveter. No room for the defiler of the corn. No room for the hommasexshul. No room -Vicky snapped it off. 'That drivel makes me sick.'</p>
<p>'What did he say?' Burt asked her. 'What did he say about corn?'</p>
<p>'I didn't hear it.' She was picking at the second clothesline knot.</p>
<p>'He said something about corn. I know he did.'</p>
<p>'I got it!' Vicky said, and the suitcase fell open in her lap. They were passing a sign that said: GATLIN 5 MI. DRIVE CAREFULLY PROTECT OUR CHILDREN. The sign had been put up by the Elks. There were .22 bullet holes in it.</p>
<p>'Socks,' Vicky said. 'Two pairs of pants... a shirt... a belt... a string tie with a -' She held it up, showing him the peeling gilt neck clasp. 'Who's that?'</p>
<p>Burt glanced at it. 'Hopalong Cassidy, I think.'</p>
<p>'Oh.' She put it back. She was crying again.</p>
<p>After a moment, Burt said: 'Did anything strike you funny about that radio sermon?'</p>
<p>'No.I heard enough of that stuff as a kid to last me for ever. I told you about it.'</p>
<p>'Didn't you think he sounded kind of young? That preacher?'</p>
<p>She uttered a mirthless laugh. 'A teenager, maybe, so what? That's what's so monstrous about that whole trip. They like to get hold of them when their minds are still rubber. They know how to put all the emotional checks and balances in. You should have been at some of the tent meetings my mother and father dragged me to. . . some of the ones I was "saved" at.</p>
<p>'Let's see. There was Baby Hortense, the Singing Marvel. She was eight. She'd come on and sing "Leaning on the Everlasting Arms" while her daddy passed the plate, telling everybody to "dig deep, now, let's not let this little child of God down." Then there was Norman Staunton. He used to preach hellfire and brimstone in this Little Lord Fauntleroy suit with short pants. He was only seven.'</p>
<p>She nodded at his look of unbelief.</p>
<p>'They weren't the only two, either. There were plenty of them on the circuit. They were good draws.' She spat the word. 'Ruby Stampnell. She was a ten-year-old faith healer. The Grace Sisters. They used to come out with little tin4oil haloes over their heads and - oh!'</p>
<p>'What is it?' He jerked around to look at her, and what she was holding in her hands. Vicky was staring at it raptly. Her slowly seining hands had snagged it on the bottom of the suitcase and had brought it up as she talked. Burt pulled over to take a better look. She gave it t6 him wordlessly.</p>
<p>It was a crucifix that had been made from twists of corn husk, once green, now dry. Attached to this by woven cornsilk was a dwarf corncob. Most of the kernels had been carefully removed, probably dug out one at a time with a pocket-knife. Those kernels remaining formed a crude cruciform figure in yellowish bas-relief. Corn-kernel eyes, each slit longways to suggest pupils. Outstretched kernel arms, the legs together, terminating in a rough indication of bare feet. Above, four letters also raised from the bonewhite cob: I N R I.</p>
<p>'That's a fantastic piece of workmanship,' he said. -'It's hideous,' she said in a flat, strained voice. 'Throw it out.' -'Vicky, the police might want to see it.'</p>
<p>'Why?'</p>
<p>'Well, I don't know why' -'Throw it out, will you please do that for me? I don't want it in the car.'</p>
<p>'I'll put it in back. And as soon as we see the cops, we'll get rid of it one way or the other. I promise. Okay?'</p>
<p>'Oh, do whatever you want with it!' she shouted at him. 'You will anyway!'</p>
<p>Troubled, he threw the thing in back, where it landed on a pile of clothes. Its corn-kernel eyes stared raptly at the T-Bird's dome light. He pulled out again, gravel splurting from beneath the tyres. 'We'll give the body and everything that was in the suitcase to the cops,' he promised. 'Then we'll be shut of it.'</p>
<p>Vicky didn't answer. She was looking at her hands. A mile further on, the endless cornfields drew away from the road, showing farmhouses and outbuildings. In one yard they saw dirty chickens pecking listlessly at the soil. There were faded cola and chewing-gum ads on the roofs of barns. They passed a tall billboard that said: ONLY JESUS SAVEs. They passed a cafe with a Conoco gas island, but Burt decided to go on into the centre of town, if there was one. If not, they could come back to the cafe. It only occurred to him after they had passed it that the parking lot had been empty except for a dirty old pickup that had looked like it was sitting on two flat tyres. Vicky suddenly began to laugh, a high, giggling sound that struck Burt as being dangerously close to hysteria.</p>
<p>'What's so funny?'</p>
<p>'The signs,' she said, gasping and hiccupping. 'Haven't you been reading them? When they called this the Bible Belt, they sure weren't kidding. Oh Lordy, there's another bunch.' Another burst of hysterical laughter escaped her, and she clapped both hands over her mouth.</p>
<p>Each sign had only one word. They were leaning on whitewashed sticks that had been implanted in the sandy shoulder, long ago by the looks; the whitewash was flaked and faded. They were coming up at eighty-foot intervals and Burt read:</p>
<p>A...CLOUD...BY...DAY...A...PILLAR...OF...FIRE...BY...NIGHT</p>
<p>'They only forgot one thing,' Vicky said, still giggling helplessly.</p>
<p>'What?' Burt asked, frowning.</p>
<p>'Burma Shave.' She held a knuckled fist against her open mouth to keep in the laughter, but her semi-hysterical giggles flowed around it like effervescent ginger-ale bubbles.</p>
<p>'Vicky, are you all right?'</p>
<p>'I will be. Just as soon as we're a thousand miles away from here, in sunny sinful California with the Rockies between us and Nebraska.'</p>
<p>Another group of signs came up and they read them silently.</p>
<p>TAKE...THIS...AND...EAT...SAITH...THE...LORD...GOD</p>
<p>Now why, Burt thought, should I immediately associate that indefinite pronoun with corn? Isn't that what they say when they give you communion? It had been so long since he had been to church that he really couldn't remember. He wouldn't be surprised if they used cornbread for holy wafer around these parts. He opened his mouth to tell Vicky that, and then thought better of it.</p>
<p>They breasted a gentle rise and there was Gatlin below them, all three blocks of it, looking like a set from a movie about the Depression. 'There'll be a constable,' Burt said, and wondered why the sight of that hick one-timetable town dozing in the sun should have brought a lump of dread into his throat.</p>
<p>They passed a speed sign proclaiming that no more than thirty was now in order, and another sign, rust-flecked, which said: YOU ARE NOW ENTERNG GATLIN, NICEST LITTLE TOWN IN NEBRASKA - OR ANYWHERE ELSE! POP. 4531. Dusty elms stood on both sides of the road, most of them diseased. They passed the Gatlin Lumberyard and a 76 gas station, where the price signs swung slowly in a hot noon breeze: REG 35.9 HI-TEST 38.9, and anotherwhich said: HI TRUCKERS DIESEL FUEL AROUND BACK.</p>
<p>They crossed Elm Street, then Birch Street, and came up on the town square. The houses lining the streets were plain wood with screened porches. Angular and functional. The lawns were yellow and dispirited. Up ahead a mongrel dog walked slowly out into the middle of Maple Street, stood looking at them for a moment, then lay down in the road with its nose on its paws.</p>
<p>'Stop,' Vicky said. 'Stop right here'. Burt pulled obediently to the curb.</p>
<p>'Turn around. Let's take the body to Grand Island. That's not too far, is it? Let's do that.'</p>
<p>'Vicky, what's wrong?'</p>
<p>'What do you mean, what's wrong?' she asked, her voice rising thinly. 'This town is empty, Burt. There's nobody here but us. Can't you feel that?' He had felt something, and still felt it. But -'It just seems that way,' he said. 'But it sure is a one-hydrant town. Probably all up in the square, having a bake sale or a bingo game.' -'There's no one here.' She said the words with a queer, strained emphasis. 'Didn't you see that 76 station back there?'</p>
<p>'Sure, by the lumberyard, so what?' His mind was elsewhere, listening to the dull buzz of a cicada burrowing into one of the nearby elms. He could smell corn, dusty roses, and fertilizer - of course. For the first time they were off the turnpike and in a town. A town in a state he had never been in before (although he had flown over it from time to time in United Airlines 747s) and somehow it felt all wrong but all right. Somewhere up ahead there would be a drugstore with a soda fountain, a movie house named the Bijou, a school named after JFK.</p>
<p>'Burt, the prices said thirty-five-nine for regular and thirty-eight-nine for high octane. Now how long has it been since anyone in this country paid those prices?' -'At least four years,' he admitted. 'But, Vicky...' -'We're right in town, Burt, and there's not a car! Not one car!</p>
<p>'Grand Island is seventy miles away. It would look funny if we took him there.' -'I don't care.' -'Look, let's just drive up to the courthouse and -, 'No!' There, damn it, there. Why our marriage is falling apart, in a nutshell. No I won't. No sir. And furthermore, I'll hold my breath till I turn blue if you don't let me have my way.</p>
<p>'Vicky,' he said. 'I want to get out of here, Burt.' -'Vicky, listen to me.'</p>
<p>'Turn around. Let's go.' -'Vicky, will you stop a minute?'</p>
<p>'I'll stop when we're driving the other way. Now let's go.'</p>
<p>'We have a dead child in the trunk of our car!' he roared at her, and took a distinct pleasure at the way she flinched, the way her face crumbled. In a slightly lower voice he went on: 'His throat was cut and he was shoved out into the road and Iran him over. Now I'm going to drive up to the courthouse or whatever they have here, and I'm going to report it. If you want to start walking towards the pike, go to it. I'll pick you up. But don't you tell me to turn around and drive seventy miles to Grand Island like we had nothing in the trunk but a bag of garbage. He happens to be some mother's son, and I'm going to report it before whoever killed him gets over the hills and far away.'</p>
<p>'You bastard,' she said, crying. 'What am I doing with you?'<br />'I don't know,' he said. 'I don't know any more. But the situation can be remedied, Vicky.'</p>
<p>He pulled away from the curb. The dog lifted its head at the brief squeal of the tyres and then lowered it to its paws again.</p>
<p>They drove the remaining block to the square. At the corner of Main and Pleasant, Main Street split in two. There actually was a town square, a grassy park with a bandstand in the middle. On the other end, where Main Street became one again, there were two official-looking buildings. Burt could make out the lettering on one: GATLIN</p>
<p>MUNICIPAL CENTER. 'That's it,' he said. Vicky said nothing.</p>
<p>Halfway up the square, Burt pulled over again. They were beside a lunch room, the Gatlin Bar and Grill. 'Where are you going?' Vicky asked with alarm as he opened his door. 'To find out where everyone is. Sign in the window there says "Open".' -'You're not going to leave me here<br />alone.' -'So come. Who's stopping you?'</p>
<p>She unlocked her door and stepped out as he crossed in front of the car. He saw how pale her face was and felt an instant of pity. Hopeless pity.</p>
<p>'Do you hear it?' she asked as he joined her.</p>
<p>'Hear what?'</p>
<p>'The nothing. No cars. No people. No tractors. Nothing.' And then, from a block over, they heard the high and joyous laughter of children.</p>
<p>'I hear kids,' he said. 'Don't you?'</p>
<p>She looked at him, troubled.</p>
<p>He opened the lunchroom door and stepped into dry, antiseptic heat. The floor was dusty. The sheen on the chrome was dull. The wooden blades of the ceiling fans stood still. Empty tables. Empty counter stools. But the mirror behind the counter had been shattered and there was something else. . . in a moment he had it. All the beer taps had been broken off. They lay along the counter like bizarre party favours.</p>
<p>Vicky's voice was gay and near to breaking. 'Sure. Ask anybody. Pardon me, sir, but could you tell me -'</p>
<p>'Oh, shut up.' But his voice was dull and without force. They were standing in a bar of dusty sunlight that fell through the lunchroom's big plate-glass window and again he had that feeling of being watched and he thought of the boy they had in their trunk, and of the high laughter of children. A phrase came to him for no reason, a legal-sounding phrase, and it began to repeat mystically in his mind: Sight unseen. Sight unseen. Sight unseen.</p>
<p>His eyes travelled over the age-yellowed cards thumb-tacked up behind the counter: CHEESEBURG 35c WORLD'S BEST JOE 10c STRAWBERRY RHUBARB PIE 25c TODAY'S SPECIAL HAM &amp; RED EYE GRAVY W/MASHED POT 80c.</p>
<p>How long since he had seen lunchroom prices like that?</p>
<p>Vicky had the answer. 'Look at this,' she said shrilly. She was pointing at the calendar on the wall. 'They've been at that bean supper for twelve years, I guess.' She uttered a grinding laugh.</p>
<p>He walked over. The picture showed two boys swimming in a pond while a cute little dog carried off their clothes. Below the picture was the legend: COMPLIMENTS OF GATLIN LUMBER &amp; HARDWARE. You Breakum, We Fixum. The month on view was August 1964.</p>
<p>'I don't understand,' he faltered, 'but I'm sure -,</p>
<p>'You're sure!' she cried hysterically. 'Sure, you're sure! That's part of your trouble, Burt, you've spent your whole life being sure!'</p>
<p>He turned back to the door and she came after him.</p>
<p>'Where are you going?'</p>
<p>'To the Municipal Center.'</p>
<p>'Burt, why do you have to be so stubborn? You know something's wrong here. Can't you just admit it?'</p>
<p>'I'm not being stubborn. I just want to get shut of what's in that trunk.'</p>
<p>They stepped out on to the sidewalk, and Burt was struck afresh with the town's silence, and with the smell of fertilizer. Somehow you never thought of that smell when you buttered an ear and salted it and bit in.<br />Compliments of sun, rain, all sorts of man-made phosphates, and a good healthy dose of cow shit. But somehow this smell was different from the one he had grown up with in rural upstate New York. You could say whatever you wanted to about organic fertilizer, but there was something almost fragrant about it when the spreader was laying it down in the fields. Not one of your great perfumes, God no, but when the late-afternoon spring breeze would pick up and waft it over the freshly turned fields, it was a smell with good associations. It meant winter was over for good. It meant that school doors were going to bang closed in six weeks or so and spill everyone out into summer. It was a smell tied irrevocably in his mind with other aromas that were perfume: timothy grass, clover, fresh earth, hollyhocks, dogwood.</p>
<p>But they must do something different out here, he thought. The smell was close but not the same. There was a sickish-sweet undertone. Almost a death smell. As a medical orderly in Vietnam, he had become well versed in that smell. Vicky was sitting quietly in the car, holding the corn crucifix in her lap and staring at it in a rapt way Burt didn't like.'Put that thing down,' he said. 'No,' she said without looking up. 'You play your games and I'll play mine.'</p>
<p>He put the car in gear and drove up to the corner. A dead stoplight hung overhead, swinging in a faint breeze. To the left was a neat white church. The grass was cut. Neatly kept flowers grew beside the flagged path up to the door. Burt pulled over.</p>
<p>'What are you doing?'</p>
<p>'I'm going to go in and take a look' Burt said. 'It's the only place in town that looks as if there isn't ten years' dust On it. And look at the sermon board.'</p>
<p>She looked. Neatly pegged white letters under glass read: THE POWER AND GRACE OF HE WHO WALKS BEHIND THE ROWS. The date was 27 July 1976 - the Sunday before.</p>
<p>'He Who Walks Behind the Rows,' Burt said, turning off the ignition. 'One of the nine thousand names of God only used in Nebraska, I guess. Coming?'</p>
<p>She didn't smile. 'I'm not going in with you.'</p>
<p>'Fine. Whatever you want.'</p>
<p>'I haven't been in a church since I left home and I don't want to be in this church and I don't want to be in this town, Burt. I'm scared Out of my mind, can't we just go?' -'I'll only be a minute.'</p>
<p>'I've got my keys, Burt. If you're not back in five minutes, I'll just drive away and leave you here.' -'Now just wait a minute, lady.'</p>
<p>'That's what I'm going to do. Unless you want to assault me like a common mugger and take my keys. I suppose you could do that.'</p>
<p>'But you don't think I will.' -'No.'</p>
<p>Her purse Was on the seat between them. He snatched it up. She screamed and grabbed for the shoulder strap. He pulled it out of her reach. Not bothering to dig, he simply turned the bag upside down and let everything fall out. Her key-ring glittered amid tissues, cosmetics, change, old shopping lists. She lunged for it but he beat her again and put the keys in his own pocket.</p>
<p>'You didn't have to do that,' she said, crying. 'Give them tome.' 'No,' he said, and gave her a hard, meaningless grin. 'No way.'</p>
<p>'Please, Burt! I'm scared!' She held her hand out, pleading now. 'You'd wait two minutes and decide that was long enough.' -'I wouldn't -'</p>
<p>'And then you'd drive off laughing and saying to yourself, "That'll teach Burt to cross me when I want something." Hasn't that pretty much been your motto during our married life? That'll teach Burt to cross me?'</p>
<p>He got out of the car. 'Please, Burt?' she screamed, sliding across the seat. 'Listen. . .I know. . . we'll drive out of town and call from a phone booth, okay? I've got all kinds of change. I just. we can . . . don't leave me alone, Burt, don't leave me out here alone!'</p>
<p>He slammed the door on her cry and then leaned against the side of the T-Bird for a moment, thumbs against his closed eyes. She was pounding on the driver's side window and calling his name. She was going to make a wonderful impression when he finally found someone in authority to take charge of the kid's body. Oh yes. He turned and walked up the flagstone path to the church doors. Two or three minutes, just a look around, and he would be back out. Probably the door wasn't even unlocked. But it pushed in easily on silent, well-oiled hinges (reverently oiled, he thought, and that seemed funny for no really good reason) and he stepped into a vestibule so cool it was almost chilly. It took his eyes a moment to adjust to the dimness.</p>
<p>The first thing he noticed was a pile of wooden letters in the far corner, dusty and jumbled indifferently together. He went to them, curious. They looked as old and forgotten as the calendar in the bar and grill, unlike the rest of the vestibule, which was dust-free and tidy. The letters were about two feet high, obviously part of a set. He spread them out on the carpet - there were eighteen of them - and shifted them around like anagrams. HURT BITE CRAG CHAP CS. Nope. CRAP TARGET CHIBS HUC. That wasn't much good either. Except for the CH in CHIBS. He quickly assembled the word CHURCH and was left looking at RAP TAGET CIBS. Foolish. He was squatting here playing idiot games with a bunch of letters while Vicky was going nuts out in the car. He started to get up, and then saw it. He formed BAPTIST, leaving RAG EC - and by changing two letters he had GRACE. GRACE BAPTIST CHURCH. The letters must have been out front. They had taken them down and had thrown them indifferently in the corner, and the church had been painted since then so that you couldn't even see where the letters had been.</p>
<p>Why? It wasn't the Grace Baptist Church any more, that was why. So what kind of church was it? For some reason that question caused a trickle of fear and he stood up quickly, dusting his fingers. So they had taken down a bunch of letters, so what? Maybe they had changed the place into Flip Wilson's Church of What's Happening Now.</p>
<p>But what had happened then?</p>
<p>He shook it off impatiently and went through the inner doors. Now he was standing at the back of the church itself, and as he looked towards the nave, he felt fear close around his heart and squeeze tightly. His breath drew in, loud in the pregnant silence of this place.</p>
<p>The space behind the pulpit was dominated by a gigantic portrait of Christ, and Burt thought: If nothing else in this town gave Vicky the screaming meemies, this would. The Christ was grinning, vulpine. His eyes were wide and staring, reminding Burt uneasily of Lon Chaney in The Phantom of the Opera. In each of the wide black pupils someone (a sinner, presumably) was drowning in a lake of fire. But the oddest thing was that this Christ had green hair hair which on closer examination revealed itself to be a twining mass of early-summer corn. The picture was crudely done but effective. It looked like a comic-strip mural done by a gifted child - an Old Testament Christ, or a pagan Christ that might slaughter his sheep for sacrifice instead of leading them. At the foot of the left-hand ranks of pews was a pipe Organ, and Burt could not at first tell what was wrong with it. He walked down the left-hand aisle and saw with slowly dawning horror that the keys had been ripped up, the stops had been pulled out . . and the pipes themselves filled with dry cornhusks. Over the organ was a carefully lettered plaque which read: MAKE NO MUSIC EXCEPT WITH HUMAN TONGUE SAITH THE LORD GOD.</p>
<p>Vicky was right. Something was terribly wrong here. He debated going back to Vicky without exploring any further, just getting into the car and leaving town as quickly as possible, never mind the Municipal Building. But it grated on him. Tell the truth, he thought. You want to give her Ban 5000 a workout before going back and admitting she was right to start with. He would go back in a minute or so.</p>
<p>He walked towards the pulpit, thinking: People must go through Gatlin all the time. There must be people in the neighbouring towns who have friends and relatives here. The Nebraska SP must cruise through from time to time. And what about the power company? The stoplight had been dead. Surely they'd know if the power had been off for twelve long years. Conclusion: What seemed to have happened in Gatlin was impossible. Still, he had the creeps.</p>
<p>He climbed the four carpeted steps to the pulpit and looked out over the deserted pews, glimmering in the half-shadows. He seemed to feel the weight of those eldritch and decidedly unchristian eyes boring into his back. There was a large Bible on the lectern, opened to the thirty-eighth chapter of Job. Burt glanced down at it and read: 'Then the Lord answered Job out of the whirlwind, and said, Who is this that darkeneth counsel by words without knowledge? . . . Where wast thou when I laid the foundations of the earth? declare, if thou hast understanding.' The lord. He Who Walks Behind the Rows. Declare if thou hast understanding. And please pass the corn.</p>
<p>He fluttered the pages of the Bible, and they made a dry whispering sound in the quiet - the sound that ghosts might make if there really were such things. And in a place like this you could almost believe it. Sections of the Bible had been chopped out. Mostly from the New Testament, he saw. Someone had decided to take on the job of amending Good King James with a pair of scissors.</p>
<p>But the Old Testament was intact. He was about to leave the pulpit when he saw another book on a lower shelf and took it out, thinking it might be a church record of weddings and confirmations and burials.</p>
<p>He grimaced at the words stamped on the cover, done inexpertly in gold leaf: THUS LET THE INIQUITOUS BE CUT DOWN SO THAT THE GROUND MAY BE FERTILE AGAIN SAITH THE LORD GOD OF HOSTS.</p>
<p>There seemed to be one train of thought around here, and Burt didn't care much for the track it seemed to ride on.</p>
<p>He opened the book to the first wide, lined sheet. A child had done the lettering, he saw immediately. In places an ink eraser had been carefully used, and while there were no misspellings, the letters were large and childishly made, drawn rather than written. The first column read:</p>
<p>Amos Deigan (Richard), b. Sept. 4, 1945<br />Sept. 4, 1964</p>
<p>Isaac Renfrew (William), b. Sept.19, 1945<br />Sept.19, 1964</p>
<p>Zepeniah Kirk (George), b. Oct.14, 1945<br />Oct.14, 1964</p>
<p>Mary Wells (Roberta), b. Nov.12, 1945<br />Nov.12, 1964</p>
<p>Yemen Hollis (Edward), b. Jan. 5, 1946<br />Jan. 5, 1965</p>
<p>Frowning, Burt continued to turn through the pages. Three-quarters of the way through, the double columns ended abruptly:</p>
<p>Rachel Stigman (Donna), b. June21, 1957<br />June 21, 1976</p>
<p>Moses Richardson (Henry), b. July 29, 1957</p>
<p>Malachi Boardman (Craig), b. August 15, 1957</p>
<p>The last entry in the book was for Ruth Clawson (Sandra), b. April 30, 1961. Burt looked at the shelf where he had found this book and came up with two more. The first had the same INIQUITOUS BE CUT DOWN logo, and it continued the same record, the single column tracing birth dates and names. In early September of 1964 he found Job Gilman (Clayton), b. September 6, and the next entry was Eve Tobin, b. June 16, 1965. No second name in parentheses. The third book was blank. Standing behind the pulpit, Burt thought about it. Something had happened in 1964. Something to do with religion, and corn. . . and children. Dear God we beg thy blessing on the crop. For Jesus' sake, amen. And the knife raised high to sacrifice the lamb - but had it been a lamb? Perhaps a religious mania had swept them. Alone, all alone, cut off from the outside world by hundreds of square miles of the rustling secret corn. Alone under seyenty million acres of blue sky. Alone under the watchful eye of God, now a strange green God, a God of corn, grown old and strange and hungry. He Who Walks Behind the Rows.</p>
<p>Burt felt a chill creep into his flesh. Vicky, let me tell you a story. It's about Amos Deigan, who was born Richard Deigan On 4 September 1945. He took the name Amos in 1964, fine Old Testament name, Amos, one of the minor prophets. Well, Vicky, what happened - don't laugh - is that Dick Deigan and his friends - Billy Renfrew, George Kirk, Roberta Wells, and Eddie Hollis among others - they got religion and they killed off their parents. All of them. Isn't that a scream? Shot them in their beds, knifed them in their bathtubs, poisoned their suppers, hung them, or disembowelled them, for all I know.</p>
<p>Why? The corn. Maybe it was dying. Maybe they got the idea somehow that it was dying because there was too much sinning. Not enough sacrifice.<br />They would have done it in the corn, in the rows. And somehow, Vicky, I'm quite sure of this, somehow they decided that nineteen was as old as any of them could live. Richard 'Amos' Deigan, the hero of our little story, had his nineteenth birthday on 4 September 1964 - the date in the book. I think maybe they killed him. Sacrificed him in the corn. Isn't that a silly story?</p>
<p>But let's look at Rachel Stigman, who was Donna Stigman until 1964. She turned nineteen on 21 June, just about a month ago. Moses Richardson was born on 29 July - just three days from today he'll be nineteen. Any idea what's going to happen to ole Mose on the twenty-ninth? I can guess. Burt licked his lips, which felt dry.</p>
<p>One other thing, Vicky. Look at this. We have Job Gilman (Clayton) born on 6 September 1964. No other births until 16 June 1965. A gap of ten months. Know what I think? They killed all the parents, even the pregnant ones, that's what I think. And one of them got pregnant in October of 1964 and gave birth to Eve. Some sixteen- or seventeen-year-old girl. Eve. The first woman.</p>
<p>He thumbed back through the book feverishly and found the Eve Tobin entry. Below it: 'Adam Greenlaw, b. July 11, 1965'. They'd be just eleven now, he thought and his flesh began to crawl. And maybe they're out there. Someplace.</p>
<p>But how could such a thing be kept secret? How could it goon? How unless the God in question approved? 'Oh Jesus,' Burt said into the silence, and that was when the T-Bird's horn began to- blare into the afternoon, one long continuous blast.</p>
<p>Burt jumped from the pulpit and ran down the centre aisle. He threw open the outer vestibule door, letting in hot sunshine, dazzling. Vicky was bold upright behind the steering wheel, both hands plastered on the horn ring, her head swivelling wildly. From all around the children were coming. Some of them were laughing gaily. They held knives, hatchets, pipes, rocks, hammers. One girl, maybe eight, with beautiful long blonde hair, held a jackhandle. Rural weapons. Not a gun among them. Burt felt a wild urge to scream out: Which of you is Adam and Eve? Who are the mothers? Who are the daughters? Fathers? Sons?</p>
<p>Declare, if thou hast understanding.</p>
<p>They came from the side streets, from the town green, through the gate in the chain-link fence around the school playground a block further east. Some of them glanced indifferently at Burt, standing frozen on the church steps, and some nudged each other and pointed and smiled the sweet smiles of children. The girls were dressed in long brown wool and faded sun-bonnets. The boys, like Quaker parsons, were all in black and wore round-crowned flat-brimmed hats. They streamed across the town square towards the car, across lawns, a few came across the front yard of what had been the Grace Baptist Church until 1964. One or two of them almost close enough to touch. 'The shotgun!' Burt yelled. 'Vicky, get the shotgun!'</p>
<p>But she was frozen in her panic, he could see that from the steps. He doubted if she could even hear him through the closed windows. They converged on the Thunderbird. The axes and hatchets and chunks of pipe began to rise and fall. My God, am I seeing this? he thought frozenly. An arrow of chrome fell off the side of the car. The hood ornament went flying. Knives crawled spirals through the sidewalls of the tyres and the car settled. The horn blared on and on. The windshield and side windows -went opaque and cracked under the onslaught. . . and then the safety glass sprayed inwards and he could see again. Vicky was crouched back, only one hand on the horn ring now, the other thrown up to protect her face. Eager young hands reached in, fumbling for the lock/unlock button. She beat them away wildly. The horn became intermittent and then stopped altogether.</p>
<p>The beaten and dented driver's side door was hauled open. They were trying to drag her out but her hands were wrapped around the steering wheel. Then one of them leaned in, knife in hand, and -His paralysis broke and he plunged down the steps, almost falling, and ran down the flagstone walk, towards them. One of them, a boy about sixteen with long long red hair spilling out from beneath his hat, turned towards him, almost casually, and something flicked through the air. Burt's left arm jerked backwards, and for a moment he had the absurd thought that the had been punched at long distance, Then the pain came, so sharp and sudden that the world went grey.</p>
<p>He examined his arm with a stupid sort of wonder. A buck and half Pensy jack-knife was growing out of it like a strange tumour. The sleeve of his J. C. Penney sports shirt was turning red. He looked at it for what seemed like for ever, trying to understand how he could have grown a jack-knife... was it possible?</p>
<p>When he looked up, the boy with red hair was almost on top of him. He was grinning, confident. 'Hey, you bastard,' Burt said. His voice was creaking, shocked.</p>
<p>'Remand your soul to God, for you will stand before His throne momentarily,' the boy with the red hair said, and clawed for Burt's eyes. Burt stepped back, pulled the Pensy out of his arm, and stuck it into the red-haired boy's throat. The gush of blood was immediate, gigantic. Burt was splashed with it. The red-haired boy began to gobble and walk in a arge circle. He clawed at the knife, trying to pull it free, and was unable. Burt watched him, jaw hanging agape. None of this was happening. It was a dream. The red-haired boy gobbled and walked. Now his sound was the only one in the hot early afternoon. The others watched, stunned.</p>
<p>This part of it wasn't in the script, Burt thought numbly. Vicky and I, we were in the script. And the boy in the corn, who was trying to run away. But not one of their own. He stared at them savagely, wanting to scream, How do you like it? The red-haired boy gave one last weak gobble, and sank to his knees. He stared up at Burt for a moment, and then his hands dropped away from the shaft of the knife, and he fell forward. A soft sighing sound from the children gathered around the Thunderbird. They stared at Burt. Burt stared back at them, fascinated . . . and that was when he noticed that Vicky was gone. 'Where is she?' he asked. 'Where did you take her?'</p>
<p>One of the boys raised a blood-streaked hunting knife towards his throat and made a sawing motion there. He grinned. That was the only answer. From somewhere in back, an older boy's voice, soft: 'Get him.' The boys began to walk towards him. Burt backed up. They began to walk faster. Burt backed up faster. The shotgun, the god-damned shotgun! Out of reach. The sun cut their shadows darkly on the green church lawn... and then he was on the sidewalk. He turned and ran.</p>
<p>'Kill him!' someone roared, and they came after him. He ran, but not quite blindly. He skirted the Municipal Building - no help there, they would corner him like a rat -and ran on up Main Street, which opened out and became the highway again two blocks further up. He and Vicky would have been on that road now and away, if he had only listened.<br />His loafers slapped against the sidewalk. Ahead of him he could see a few more business buildings, including the Gatlin Ice Cream Shoppe and - sure enough - the Bijou Theatre. The dust-clotted marquee letters read NOW HOWING L MITED EN AGEMEN ELI A TH TAYLOR CLEOPA RA. Beyond the next cross street was a gas station that marked the edge of town. And beyond that the corn, closing back in to the sides of the road. A green tide of corn. Burt ran. He was already out of breath and the knife wound in his upper arm was beginning to hurt. And he wasleaving a trail of blood. As he ran he yanked his handkerchief from his back pocket and stuck it inside his shirt.</p>
<p>He ran. His loafers pounded the cracked cement of the sidewalk, his breath rasped in his throat with more and more heat. His arm began to throb in earnest. Some mordant part of his brain tried to ask if he thought he could run all the way to the next town, if he could run twenty miles of two-lane blacktop. He ran. Behind him he could hear them, fifteen years younger and faster than he was, gaining. Their feet slapped on the pavement. They whooped and shouted back and forth to each other. They're having more fun than a five-alarm fire, Burt thought disjointedly. They'll talk about it for years.</p>
<p>Burt ran. He ran past the gas station marking the edge of town. His breath gasped and roared in his chest. The sidewalk ran out under his feet. And now there was only one thing to do, only one chance to beat them and escape with his life. The houses were gone, the town was gone. The corn had surged in a soft green wave back to the edges of the road. The green, swordlike leaves rustled softly. It would be deep in there, deep and cool, shady in the rows of man-high corn.</p>
<p>He ran past a sign that said: YOU ARE NOW LEAVING GATLIN, NICEST LITTLE TOWN IN NEBRASKA - OR ANYWHERE ELSE! DROP IN ANYTIME!</p>
<p>I'll be sure to do that, Burt thought dimly.</p>]

@skingCOTK_2 = %Q[<p>He ran past the sign like a sprinter closing on the tape and then swerved left, crossing the road, and kicked his loafers away. Then he was in the corn and it closed behind him and over him like the waves of a green sea, taking him in. Hiding him. He felt a sudden and wholly unexpected relief sweep him, and at the same moment he got his second wind. His lungs, which had been shallowing up, seemed to unlock and give him more breath.</p>
<p>He ran straight down the first row he had entered, head ducked, his broad shoulders swiping the leaves and making them tremble. Twenty yards in' he turned right, parallel to the road again, and ran on, keeping low so they wouldn't see his dark head of hair bobbing amid the yellow corn tassels. He doubled back towards the road for a few moments, crossed more rows, and then put his back to the road and hopped randomly from row to row, always delving deeper and deeper into the corn. At last, he collapsed on to his knees and put his forehead against the ground. He could only hear his own taxed breathing, and the thought that played over and over in his mind was: Thank God I gave up smoking, thank God I gave up smoking, thank God -Then he could hear them, yelling back and forth to each other, in some cases bumping into each other ('Hey, this is my row!'), and the sound heartened him. They were well away to his left and they sounded very poorly organized.</p>
<p>He took his handkerchief out of his shirt, folded it, and stuck it back in after looking at the wound. The bleeding seemed to have stopped in spite of the workout he had given it.</p>
<p>He rested a moment longer, and was suddenly aware that he felt good, physically better than he had in years excepting the throb of his arm. He felt well exercised, and suddenly grappling with a clearcut (no matter how insane) problem after two years of trying to cope with the incubotic gremlins that were sucking his marriage dry. It wasn't right that he should feel this way, he told himself. He was in deadly peril of his life, and his wife had been carried off. She might be dead now. He tried to summon up Vicky's face and dispel some of the odd good feeling by doing so, but her face wouldn't come. What came was the red-haired boy with the knife in his throat.</p>
<p>He became aware of the corn fragrance in his nose now, all around him. The wind through the tops of the plants made a sound like voices. Soothing. Whatever had been done in the name of this corn, it was now his protector. But they were getting closer. Running hunched over, he hurried up the row he was in, crossed over, doubled back, and crossed over more rows. He tried to keep the voices always on his left, but as the afternoon progressed, that became harder to do. The voices had grown faint, and often the rustling sound of the corn obscured them altogether. He would run, listen, run again. The earth was hard-packed, and his stockinged feet left little or no trace.</p>
<p>When he stopped much later the sun was hanging over the fields to his right, red and inflamed, and when he looked at his watch he saw that it was quarter past seven. The sun had stained the corntops a reddish gold, but here the shadows were dark and deep. He cocked his head, listening. With the coming of sunset the wind had died entirely and the corn stood still, exhaling its aroma of growth into the warm air. If they were still in the corn they were either far away or just hunkered down and listening. But Burt didn't think a bunch of kids, even crazy ones, could be quiet for that long. He suspected they had done the most kidlike thing, regardless of the consequences for them; they had given up and gone home.</p>
<p>He turned towards the setting sun, which had sunk between the raftered clouds on the horizon, and began to walk. If he cut on a diagonal through the rows, always keeping the setting sun ahead of him, he would be bound to strike Route 17 sooner or later.</p>
<p>The ache in his arm had settled into a dull throb that was nearly pleasant, and the good feeling was still with him. He decided that as long as he was here, he would let the good feeling exist in him without guilt. The guilt would return when he had to face the authorities and account for what had happened in Gatlin. But that could wait.</p>
<p>He pressed through the corn, thinking he had never felt so keenly aware. Fifteen minutes later the sun was only a hemisphere poking over the horizon and he stopped again, his new awareness clicking into a pattern he didn't like. It was vaguely. . . well, vaguely frightening. He cocked his head. The corn was rustling.</p>
<p>Burt had been aware of that for some time, but he had just put it together with something else. The wind was still.<br />How could that be?</p>
<p>He looked around warily, half expecting to see the smiling boys in their Quaker coats creeping out of the corn, their knives clutched in their hands. Nothing of the sort. There was still that rustling noise. Off to the left.</p>
<p>He began to walk in that direction, not having to bull through the corn any more. The row was taking him in the direction he wanted to go, naturally. The row ended up ahead. Ended? No, emptied out into some sort of clearing. The rustling was there.</p>
<p>He stopped, suddenly afraid. The scent of the corn was strong enough to be cloying. The rows held on to the sun's heat and he became aware that he was plastered with sweat and chaff and thin spider strands of cornsilk. The bugs ought to be crawling all over him. . . but they weren't.</p>
<p>He stood still, staring towards that place where the corn opened out on to what looked like a large circle of bare earth.</p>
<p>There were no minges or mosquitoes in here, no black-flies or chiggers - what he and Vicky had called 'drive-in bugs' when they had been courting, he thought with sudden and unexpectedly sad nostalgia. And he hadn't seen a single crow. How was that for weird, a cornpatch with no crows?<br />In the last of the daylight he swept his eyes closely over the row of corn to his left. And saw that every leaf and stalk was perfect, which was just not possible. No yellow blight. No tattered leaves, no caterpillar eggs, no burrows, no -His eyes widened.</p>
<p>My God, there aren't any weeds!</p>
<p>Not a single one. Every foot and a half the corn plants rose from the earth. There was no witchgrass, jimson, pikeweed, whore's hair, or poke salad. Nothing.</p>
<p>Burt stared up, eyes wide. The light in the west was fading. The raftered clouds had drawn back together. Below them the golden light had faded to pink and ochre. It would be dark soon enough.</p>
<p>It was time to go down to the clearing in the corn and see what was there - hadn't that been the plan all along? All the time he had thought he was cutting back to the highway, hadn't he been being led to this place?</p>
<p>Dread in his belly, he went on down to the row and stood at the edge of the clearing. There was enough light for him to see what was here. He couldn't scream. There didn't seem to be enough air left in his lungs. He tottered in on legs like slats of splintery wood. His eyes bulged from his sweaty face.</p>
<p>'Vicky,' he whispered. 'Oh, Vicky, my God -'</p>
<p>She had been mounted on a crossbar like a hideous trophy, her arms held at the wrists and her legs at the ankles with twists of common barbed wire, seventy cents a yard at any hardware store in Nebraska. Her eyes had been ripped out. The sockets were filled with the moonflax of cornsilk. Her jaws were wrenched open in a silent scream, her mouth filled with cornhusks.</p>
<p>On her left was a skeleton in a mouldering surplice. The nude jawbone grinned. The eye sockets seemed to stare at Burt jocularly, as if the one-time minister of the Grace Baptist Church was saying: It's not so bad, being sacrificed by pagan devil-children in the corn is not so bad, having your eyes ripped out of your skull according to the Laws of Moses is not so bad -To the left of the skeleton in the surplice was a second skeleton, this one dressed in a rotting blue uniform. A hat hung over the skull, shading the eyes, and on the peak of the cap was a greenish-tinged badge reading police chief.</p>
<p>That was when Burt heard it coming: not the children but something much larger, moving through the corn and towards the clearing. Not the children, no. The children wouldn't venture into the corn at night. This was the holy place, the place of He Who Walks Behind the Rows.</p>
<p>Jerkily Burt turned to flee. The row he had entered the clearing by was gone. Closed up. All the rows had closed up. It was coming closer now and he could hear it, pushing through the corn. He could hear it breathing. An ecstasy of superstitious terror seized him. It was coming. The corn on the far side of the clearing had suddenly darkened, as if a gigantic shadow had blotted it out.</p>
<p>Coming.</p>
<p>He Who Walks Behind the Rows.</p>
<p>It began to come into the clearing. Burt saw something huge, bulking up to the sky . . . something green with terrible red eyes the size of footballs.</p>
<p>Something that smelled like dried cornhusks years in some dark barn.</p>
<p>He began to scream. But he did not scream long.</p>
<p>Some time later, a bloated orange harvest moon came up.</p>
<p>The children of the corn stood in the clearing at midday, looking at the two crucified skeletons and the two bodies. The bodies were not skeletons yet, but they would be. In time. And here, in the heartlands of Nebraska, in the corn, there was nothing but time.</p>
<p>'Behold, a dream came to me in the night, and the Lord did shew all this to me.'</p>
<p>They all turned to look at Isaac with dread and wonder, even Malachi. Isaac was only nine, but he had been the Seer since the corn had taken David a year ago. David had been nineteen and he had walked into the corn on his birthday, just as dusk had come drifting down the summer rows.</p>
<p>Now, small face grave under his round-crowned hat, Isaac continued:</p>
<p>'And in my dream the Lord was a shadow that walked behind the rows, and he spoke to me in the words he used to our older brothers years ago. He is much displeased with this<br />sacrifice.' They made a sighing, sobbing noise and looked at the surrounding walls of green.</p>
<p>'And the Lord did say: Have I not given you a place of killing, that you might make sacrifice there? And have I not shewn you favour? But this man has made a blasphemy within me, and I have completed this sacrifice myself.<br />Like the Blue Man and the false minister who escaped many years ago.'</p>
<p>'The Blue Man . . . the false minister,' they whispered, and looked at each other uneasily.</p>
<p>'So now is the Age of Favour lowered from nineteen plantings and harvestings to eighteen,' Isaac went on relentlessly. 'Yet be fruitful and multiply as the corn multiplies, that my favour may be shewn you, and be upon you.' Isaac ceased.</p>
<p>The eyes turned to Malachi and Joseph, the only two among this party who were eighteen. There were others back in town, perhaps twenty in all. They waited to hear what Malachi would say, Malachi who had led the hunt for Japheth, who evermore would be known as Ahaz, cursed of God. Malachi had cut the throat of Ahaz and had thrown his body out of the corn so the foul body would not pollute it or blight it.</p>
<p>'I obey the word of God,' Malachi whispered. The corn seemed to sigh its approval. In the weeks to come the girls would make many corncob crucifixes to ward off further evil.</p>
<p>And that night all of those now above the Age of Favour walked silently into the corn and went to the clearing, to gain the continued favour of He Who Walks Behind the Rows.</p>
<p>'Goodbye, Malachi,' Ruth called. She waved disconsolately. Her belly was big with Malachi's child and tears coursed silently down her cheeks. Malachi did not turn. His back was straight. The corn swallowed him.</p>
<p>Ruth turned away, still crying. She had conceived a secret hatred for the corn and sometimes dreamed of walking into it with a torch in each hand when dry September came and the stalks were dead and explosively combustible. But she also feared it. Out there, in the night, something walked, and it saw everything . . even the secrets kept in human hearts. Dusk deepened into night. Around Gatlin the corn rustled and whispered secretly.</p>
<p>It was well pleased.</p>]
